"use client";

/**
 * Who may use the admin console — the superadmin's own surface (`/v1/admin/operators`).
 *
 * ══ WHAT THE TWO TIERS ARE ══════════════════════════════════════════════════════════
 *
 * `superadmin` holds every permission in `core/rbac.Permission`, by derivation rather
 * than by a hand-kept list, and `operator` — the NORMAL admin tier — holds the subset
 * that runs onboarding and support (named, not counted: a count in prose is the defect
 * class D-103/D-105 exist for). What it deliberately does NOT hold is the four that
 * decide what the platform itself does: `platform:secrets`, `platform:config`,
 * `ops:manage` and `admin:operators`. The last of those is this surface, and it is what
 * makes the split real rather than cosmetic: a normal admin cannot reach the table that
 * decides who is a normal admin, so no request they can send widens their own authority.
 *
 * ══ THERE IS NO CREDENTIAL, NO TOKEN AND NO SETUP LINK IN THIS FILE ═════════════════
 *
 * Not on a response type, not in a hook's return, not in a mutation's variables.
 * `OperatorOut` carries `activated` — WHETHER a password exists — and nothing else about
 * one. The setup link goes to the invited mailbox and nowhere else, which is D-190's
 * finding on the client realm (a token the inviter can see is a token the inviter can
 * redeem, i.e. an account squat) applied to the account type that can install vendor
 * credentials. The API has no field to put one in; neither does this.
 *
 * ══ THE TYPES ARE HAND-WRITTEN, AND THAT IS TEMPORARY ═══════════════════════════════
 *
 * `src/lib/api/schema.d.ts` is regenerated by `pnpm gen:api` from the API's OpenAPI
 * snapshot as one step at the end of a change, and this surface landed after the
 * snapshot in `src/lib/api/openapi.json` was taken — `grep admin/operators` finds
 * nothing there. So these mirror `apps/api/admin/operator_routes.py`'s response models
 * field for field until that runs, exactly as `leadSources.ts`'s provisioning types
 * mirror `ingest/routes.py`. Swap each for `Schemas["OperatorOut"]` and friends the
 * moment the snapshot carries them; the shape below is what that swap must produce.
 *
 * EVERY FIELD IS REQUIRED HERE ON PURPOSE, including the two nullable ones. `OperatorOut`
 * declares no Pydantic defaults, so nothing on it is optional on the wire — and a
 * hand-written twin that made `activated` optional is how `activated: undefined` becomes
 * a row that offers neither "resend the setup link" nor "revoke", which is this repo's
 * most repeated frontend defect (`leadSources.ts` names it too).
 */

import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseQueryResult,
} from "@tanstack/react-query";

import { adminSession } from "./admin";
import { apiRequest } from "./client";

export const OPERATORS_PATH = "/v1/admin/operators";

/**
 * One key for the whole realm — no slug, nothing tenant-derived.
 *
 * `tests/queryKeys.test.ts` requires exactly this: a `queryFn` built on `adminSession()`
 * belongs to no org, so an org-scoped key here would be a discriminator that names a
 * tenant this document has nothing to do with.
 */
export const OPERATORS_QUERY_KEY = ["admin", "operators"] as const;

/** The two tiers, as `core/rbac.ADMIN_ROLES` spells them. */
export type AdminRole = "superadmin" | "operator";

/**
 * The order the picker offers them in: the NARROW tier first.
 *
 * Not alphabetical and not "most powerful first". `OperatorCreateIn.role` defaults to
 * `operator` on the API for the founder's own reason — "I can add more admins who are
 * NOT super admins" — and a `<select>` whose first option is the default is the one whose
 * accidental submission is the safe act.
 */
export const ADMIN_ROLES: AdminRole[] = ["operator", "superadmin"];

/**
 * One operator account, as `GET /v1/admin/operators` returns it.
 *
 * `email` and `name` are nullable for Clerk-era rows only (D-177); every account created
 * through this console has an address, because the API requires one to mail the setup
 * link to. `created_at` is an ISO instant as a STRING — the API serialises it with
 * `.isoformat()` — and is rendered through `formatIST` like every other instant in both
 * consoles.
 */
export interface Operator {
  id: string;
  email: string | null;
  name: string | null;
  role: string;
  created_at: string;
  /** False while the setup link is outstanding: the account exists and cannot sign in. */
  activated: boolean;
}

export interface OperatorList {
  operators: Operator[];
}

/* ── The four step-up confirmations, copied VERBATIM from the API ──────────────────────
 *
 * `apps/api/admin/operator_routes.py` builds these four strings and refuses anything
 * else with `step_up_required`, so a drift here is a visible refusal rather than a silent
 * bypass — the same arrangement `opsConfig.ts`, `opsSecrets.ts` and `erasure.ts` have
 * with their own routes. They are copied rather than derived from a shared constant for
 * the reason those files copy theirs: this is a property of the request being sent, and
 * a mismatch is the server's to detect.
 *
 * THE TWO BINDINGS DIFFER, AND THE API ARGUES WHY. Creation is bound to the ROLE, because
 * there is no subject yet and because consent to add a colleague who can onboard clients
 * is not consent to add a second holder of every platform secret. The other three are
 * bound to the SUBJECT, because there the subject is the whole question — a confirmation
 * typed to promote Asha must not lift Ravi. Neither is bound to an email ADDRESS: these
 * strings travel in a header, and a header lands in access logs (hard rule 6).
 */

export function addOperatorConfirmation(role: AdminRole): string {
  return `add_operator:${role}`;
}

export function operatorRoleConfirmation(operatorId: string): string {
  return `set_operator_role:${operatorId}`;
}

export function operatorRevocationConfirmation(operatorId: string): string {
  return `revoke_operator:${operatorId}`;
}

export function operatorSetupLinkConfirmation(operatorId: string): string {
  return `reissue_operator_setup_link:${operatorId}`;
}

/**
 * One account's path. `encodeURIComponent`, like `erasure.ts` and `holds.ts` build theirs.
 *
 * The ids are uuid_v7 off our own wire, so nothing here needs escaping today — and that
 * is exactly the reasoning that ends with a raw interpolation the day an identifier stops
 * being a uuid. The encode costs a function call and removes the question.
 */
function operatorPath(operatorId: string, suffix = ""): string {
  return `${OPERATORS_PATH}/${encodeURIComponent(operatorId)}${suffix}`;
}

export function useOperators(): UseQueryResult<OperatorList> {
  return useQuery({
    queryKey: OPERATORS_QUERY_KEY,
    queryFn: () => apiRequest<OperatorList>(adminSession(), OPERATORS_PATH),
    // The allowlist changes when somebody on this screen changes it, and every mutation
    // below invalidates the key. `teamKeys` uses the same minute for the same reason.
    staleTime: 60_000,
  });
}

function invalidate(client: ReturnType<typeof useQueryClient>): void {
  void client.invalidateQueries({ queryKey: OPERATORS_QUERY_KEY });
}

export interface AddOperatorInput {
  email: string;
  name: string | null;
  role: AdminRole;
  /** Required, ≥3 characters after trimming — `_Reasoned` on the API refuses less. */
  reason: string;
}

export function useAddOperator() {
  const client = useQueryClient();
  return useMutation({
    mutationFn: ({ email, name, role, reason }: AddOperatorInput) =>
      apiRequest<Operator>(adminSession(), OPERATORS_PATH, {
        method: "POST",
        body: { email, name, role, reason },
        confirmAction: addOperatorConfirmation(role),
      }),
    onSuccess: () => invalidate(client),
  });
}

export function useSetOperatorRole() {
  const client = useQueryClient();
  return useMutation({
    mutationFn: ({
      operatorId,
      role,
      reason,
    }: {
      operatorId: string;
      role: AdminRole;
      reason: string;
    }) =>
      apiRequest<Operator>(adminSession(), operatorPath(operatorId), {
        method: "PATCH",
        body: { role, reason },
        confirmAction: operatorRoleConfirmation(operatorId),
      }),
    onSuccess: () => invalidate(client),
  });
}

/**
 * End an account — a POST to `/revocation`, never a DELETE, and the verb is the contract.
 *
 * Nothing is deleted. Eight tables reference `admin_users` `ON DELETE RESTRICT` because
 * they record which operator approved a campaign, verified a KYC record or installed a
 * credential (migration f2c74b81a9d3), so the row survives its account and
 * `deactivated_at` is what ends it. A `DELETE` here would promise an erasure this surface
 * does not perform — and would have nowhere to carry the reason the API requires, since a
 * body on `DELETE` is the one shape HTTP intermediaries feel free to drop.
 */
export function useRevokeOperator() {
  const client = useQueryClient();
  return useMutation({
    mutationFn: ({
      operatorId,
      reason,
    }: {
      operatorId: string;
      reason: string;
    }) =>
      apiRequest<Operator>(
        adminSession(),
        operatorPath(operatorId, "/revocation"),
        {
          method: "POST",
          body: { reason },
          confirmAction: operatorRevocationConfirmation(operatorId),
        },
      ),
    onSuccess: () => invalidate(client),
  });
}

/**
 * Re-mail the setup link for an account that never finished signing in.
 *
 * IT IS NOT A PASSWORD RESET AND THE SCREEN MUST NOT OFFER IT AS ONE: the API refuses an
 * account that already has a password (`operator_already_activated`), and somebody who
 * has forgotten theirs uses the sign-in page, which mails the link to THEM rather than to
 * the person asking on their behalf.
 */
export function useResendOperatorSetupLink() {
  const client = useQueryClient();
  return useMutation({
    mutationFn: ({
      operatorId,
      reason,
    }: {
      operatorId: string;
      reason: string;
    }) =>
      apiRequest<Operator>(
        adminSession(),
        operatorPath(operatorId, "/setup-link"),
        {
          method: "POST",
          body: { reason },
          confirmAction: operatorSetupLinkConfirmation(operatorId),
        },
      ),
    onSuccess: () => invalidate(client),
  });
}

/**
 * What each tier actually means, in the words the person deciding needs.
 *
 * Kept beside the control that sets it rather than in a tooltip, exactly as `ROLE_COPY`
 * is on the client realm's team screen: "superadmin" and "operator" are OUR words, and
 * somebody choosing between them is deciding whether this person can replace the Bolna
 * key and add further administrators without being told so anywhere else.
 *
 * The `cannot` line mirrors `core/rbac.SUPERADMIN_ONLY_PERMISSIONS` — the four
 * permissions `ROLE_PERMISSIONS["operator"]` omits, which since the founder's correction
 * to D-457 are the WHOLE difference between the tiers. If that set changes, this copy is
 * the other half of the change, and `tests/adminOperators.test.tsx` reads the role table
 * on disk to make sure it is.
 *
 * The `can` line says the raw reads out loud on purpose. "Support across every client" is
 * true and comfortable; "can play the recording and take the contact list, attributably"
 * is what somebody is actually granting, and this screen is where they grant it.
 */
export const ROLE_COPY: Record<
  string,
  { label: string; can: string; cannot: string | null }
> = {
  superadmin: {
    label: "Super admin",
    can: "Everything on the platform, including the vendor API keys, the platform configuration, the big red switch, and adding or removing other admins.",
    cannot: null,
  },
  operator: {
    label: "Admin",
    can: "Onboarding and support across every client: agents, calls, leads, knowledge bases, client settings, campaign dispatch, view-as — and, inside a view-as session, the unredacted transcript, the recording and the contact export, each of which writes an audit row naming them.",
    cannot:
      "Cannot see or change the vendor API keys, cannot change platform configuration, cannot use the incident switches, and cannot add or remove admins.",
  },
};

/**
 * Somebody's name for a screen, without ever inventing one.
 *
 * `name` is nullable and `email` is nullable, and the fallback ladder ends at the id
 * rather than at a word like "Unnamed" that two different accounts would share — this is
 * a list whose whole purpose is telling two administrators apart, and a shared label on
 * a Revoke button is how the wrong one gets revoked.
 */
/**
 * What a person types to confirm an action against ONE account.
 *
 * THE ADDRESS FIRST, where `operatorLabel` takes the name first, and the difference is
 * the job. A label identifies a row to a reader who is already looking at it; a
 * confirmation has to be the thing somebody would most regret getting wrong, and two
 * colleagues can share a name in a way they cannot share a mailbox. It is also the field
 * the setup link was mailed to, so it is the identity an operator actually holds in mind.
 *
 * NEVER SENT. `X-Confirm-Action` still carries the API's id-bound string — a header lands
 * in access logs, and a mailbox in an access log is hard rule 6. This phrase is compared
 * in the browser and goes no further.
 */
export function operatorConfirmPhrase(operator: Operator): string {
  return operator.email ?? operator.name ?? `account ${operator.id}`;
}

export function operatorLabel(operator: Operator): string {
  return operator.name ?? operator.email ?? `account ${operator.id}`;
}

/**
 * The tier a change would move this account TO, or `null` when the console cannot say.
 *
 * WITH TWO TIERS THERE IS ONLY ONE MOVE PER ROW, which is why this screen states the
 * change instead of offering a picker — a two-value `<select>` whose only useful setting
 * is the one they are not on is a control that asks a question with one answer. It is
 * also what makes the API's subject-bound confirmation (`set_operator_role:<id>`) name
 * the act completely: given the row, the destination is not a free choice.
 *
 * `null` IS THE IMPORTANT RETURN, and it is not hypothetical. `Operator.role` is a WIRE
 * string, and a deployment whose API is newer than this build could send a third tier.
 * The obvious spelling — `role === "superadmin" ? "operator" : "superadmin"` — reads an
 * unrecognised tier as "not a super admin" and offers to PROMOTE it, which is the one
 * direction a wrong guess must never take. So an unknown tier gets no control and a
 * sentence, the same way `RoleBadge` renders the wire string rather than inventing a
 * label for it.
 */
export function tierChangeTarget(operator: Operator): AdminRole | null {
  if (operator.role === "superadmin") return "operator";
  if (operator.role === "operator") return "superadmin";
  return null;
}

/**
 * May this session act on THIS row — and if not, what does the operator need to read?
 *
 * `null` means "offer the controls". A string is the sentence that replaces them, and it
 * is deliberately the sentence rather than a disabled button: the API refuses these two
 * acts outright (`operator_self_administration`), so there is no state in which the
 * control could work and a greyed-out one would be a control that is never available.
 *
 * THIS IS THE LOCKOUT GUARD, and it is worth stating exactly what makes it one, because
 * "the last superadmin cannot be removed" is not implemented as a count anywhere.
 * `authn/operators.py` argues it as a consequence of three facts rather than as a fourth
 * check: only a superadmin may demote or revoke, no operator may aim either act at
 * themselves, and authority is re-read from `admin_users` on every request. So the actor
 * is always a live superadmin who is not the subject, and the platform still has one when
 * the statement commits. A `SELECT count(*) WHERE role = 'superadmin'` guard would read
 * as prudent and could never fire.
 *
 * The console's job is therefore NOT to re-derive that invariant — a second opinion about
 * who the last superadmin is, computed from a list that may be one refetch stale, is
 * exactly the class of screen-side re-derivation `tm_registration.is_live` exists as a
 * warning about. Its job is to make the one refusal that holds the invariant up visible
 * BEFORE the click, and to say why, so the founder meets a sentence instead of a 403 on
 * the request that would have ended their own access.
 */
export function selfAdministrationBlock(
  operator: Operator,
  viewerId: string | null,
): string | null {
  if (viewerId === null || operator.id !== viewerId) return null;
  return (
    "This is your own account. You cannot change your own role or revoke your own " +
    "access — every change to this list names two different people, which is also what " +
    "stops the last super admin removing themselves. Ask another super admin."
  );
}
