"use client";

/**
 * Lead-source (inbound ingest) hooks — SURFACES §2b.
 *
 * These two endpoints answer the two questions webhook ingest generates:
 * "did my form's submission arrive?" (activity) and "would it have triggered a
 * call?" (dry-run test). The dry-run consults the compliance gate without acting
 * on it — see apps/api/ingest/routes.py `test_webhook` for why that is not a
 * gate bypass.
 *
 * The ACTIVITY shapes are aliased from the generated schema. The DRY-RUN shapes below
 * are hand-written for one more regeneration only: `POST /v1/lead-sources/{id}/test`
 * NOW answers `LeadSourceDryRunOut` — it used to return a plain dict, which is why they
 * were written by hand in the first place — so they become
 * `Schemas["LeadSourceDryRunOut"]` and `Schemas["LeadSourceDryRunStepOut"]` at the next
 * `pnpm gen:api`, exactly as the activity types did. Mirrored field for field until then.
 */

import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseQueryResult,
} from "@tanstack/react-query";

import { apiRequest, type Session } from "./client";
import type { components } from "./schema";

type Schemas = components["schemas"];

const listKey = (session: Session) => ["lead-sources", session.orgSlug];

/**
 * One inbound source's rolled-up delivery record from the durable inbox.
 *
 * Two things the hand-written interface this replaces got wrong, both now fixed by
 * the server's own model: `event` is NULLABLE (a vendor that posts without an event
 * name is a delivery we still record, and the old type made it unrepresentable), and
 * `first_at` / `last_at` are NOT NULL — an inbox row cannot exist without the
 * timestamps that created and last touched it.
 *
 * `outcome` is the three words the SURFACES spec uses, not the internal inbox enum;
 * `deduplicated` counts vendor retries we absorbed without ringing the customer twice.
 */
export type IngestActivityItem = Schemas["IngestActivityItemOut"];

export type IngestActivity = Schemas["IngestActivityOut"];

/**
 * One decision the real ingest path would have made, reported instead of acted on.
 *
 * `step` is the server's closed set, so a screen can switch on it exhaustively. Nothing
 * here carries the sample's own values: `mapped_fields` is the client's configured field
 * NAMES, and the number the dry run normalized to answer the question never leaves the
 * server (apps/api/ingest/routes.py).
 */
export interface LeadSourceDryRunStep {
  step: "field_mapping" | "phone_number" | "agent" | "form_consent" | "compliance_gate";
  ok: boolean;
  detail: string;
  /** The compliance gate's rule on the gate step; null on every other. */
  rule?: string | null;
  /** Which configured fields the sample filled in — null where the question does not
   *  apply, `[]` when the mapping matched nothing in this sample. */
  mapped_fields?: string[] | null;
}

export interface LeadSourceDryRun {
  would_call: boolean;
  steps: LeadSourceDryRunStep[];
}

export function useIngestActivity(session: Session): UseQueryResult<IngestActivity> {
  return useQuery({
    queryKey: ["ingest-activity", session.orgSlug],
    queryFn: () => apiRequest<IngestActivity>(session, "/v1/lead-sources/activity"),
    // Deliveries land on the form vendor's schedule, and this screen is usually
    // open precisely because someone just submitted a test form and is waiting
    // to see it appear. 30s keeps that loop tight without hammering the inbox.
    refetchInterval: 30_000,
  });
}

/**
 * Callback URL, verify token and capability for a Meta Lead Ads source.
 *
 * `MetaSetupOut` from the generated schema — not a hand-written twin, because the
 * field this screen most needs to be right about is `lead_retrieval_available`, and a
 * local interface is exactly how a `false` becomes an optional `undefined` that reads
 * as "fine".
 *
 * **A mutation, deliberately, for a call that reads nothing.** The endpoint is a POST
 * because the RESPONSE carries a credential (the `hub.verify_token`) — the mirror of
 * `/v1/dnc/check`, which is a POST because the REQUEST does. Modelling it as a query
 * would have this page fetch a credential on every mount, cache it, refetch it on
 * window focus and keep it in memory behind whatever the user navigated to next. A
 * mutation fetches it once, when someone explicitly asks for it, and forgets it when
 * the screen unmounts.
 */
export type MetaSetup = Schemas["MetaSetupOut"];

export function useMetaSetup(session: Session) {
  return useMutation({
    mutationFn: (webhookId: string) =>
      apiRequest<MetaSetup>(session, `/v1/lead-sources/${webhookId}/meta/setup`, {
        method: "POST",
      }),
  });
}

/**
 * Provisioning (SURFACES §2b) — the half that used to be an operator running SQL.
 *
 * HAND-WRITTEN, like the dry-run shapes above and for the same reason: the generated
 * `schema.d.ts` is regenerated by `pnpm gen:api` as one step at the end of a change,
 * so these mirror `apps/api/ingest/routes.py`'s response models until that runs. Swap
 * them for `Schemas["LeadSourceOut"]` and friends the way the activity types were.
 */
export interface LeadSource {
  id: string;
  source: string;
  agent_id: string | null;
  active: boolean;
  mapping: Record<string, string>;
  /** Which secret we hold — never the secret. */
  secret_fingerprint: string;
  /** Set only while a rotation grace window is open; null the moment it closes. */
  previous_secret_expires_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface LeadSourceList {
  items: LeadSource[];
  /** The header a sender puts the secret in. Served, not hardcoded here, so the
   *  instructions on screen cannot drift from what the receiver reads. */
  secret_header: string;
}

/** The only response that ever carries a plaintext secret. */
export interface NewLeadSource {
  id: string;
  source: string;
  ingest_path: string;
  /** Null for Meta: the client supplied their own App Secret, so nothing was minted. */
  secret: string | null;
  secret_header: string;
}

export interface RotatedSecret {
  id: string;
  secret: string | null;
  secret_header: string;
  previous_secret_expires_at: string | null;
}

export interface CreateLeadSourceInput {
  source: string;
  agent_id?: string | null;
  mapping?: Record<string, string>;
  app_secret?: string;
}

export function useLeadSources(session: Session): UseQueryResult<LeadSourceList> {
  return useQuery({
    queryKey: listKey(session),
    queryFn: () => apiRequest<LeadSourceList>(session, "/v1/lead-sources"),
  });
}

export function useCreateLeadSource(session: Session) {
  const client = useQueryClient();
  return useMutation({
    mutationFn: (input: CreateLeadSourceInput) =>
      apiRequest<NewLeadSource>(session, "/v1/lead-sources", { method: "POST", body: input }),
    onSuccess: () => void client.invalidateQueries({ queryKey: listKey(session) }),
  });
}

export function useRotateLeadSourceSecret(session: Session) {
  const client = useQueryClient();
  return useMutation({
    mutationFn: ({
      webhookId,
      graceMinutes,
      appSecret,
    }: {
      webhookId: string;
      graceMinutes: number;
      appSecret?: string;
    }) =>
      apiRequest<RotatedSecret>(session, `/v1/lead-sources/${webhookId}/rotate-secret`, {
        method: "POST",
        body: { grace_minutes: graceMinutes, ...(appSecret ? { app_secret: appSecret } : {}) },
      }),
    // The list carries the fingerprint and the grace deadline, both of which this
    // just changed.
    onSuccess: () => void client.invalidateQueries({ queryKey: listKey(session) }),
  });
}

export function useSetLeadSourceActive(session: Session) {
  const client = useQueryClient();
  return useMutation({
    mutationFn: ({ webhookId, active }: { webhookId: string; active: boolean }) =>
      active
        ? apiRequest<void>(session, `/v1/lead-sources/${webhookId}/enable`, { method: "POST" })
        : apiRequest<void>(session, `/v1/lead-sources/${webhookId}`, { method: "DELETE" }),
    onSuccess: () => void client.invalidateQueries({ queryKey: listKey(session) }),
  });
}

export function useTestWebhook(session: Session) {
  return useMutation({
    // No cache invalidation on success: the dry-run writes nothing server-side
    // (no lead row, no inbox row), so there is nothing stale to refetch.
    mutationFn: ({ webhookId, payload }: { webhookId: string; payload: object }) =>
      apiRequest<LeadSourceDryRun>(session, `/v1/lead-sources/${webhookId}/test`, {
        method: "POST",
        body: { payload },
      }),
  });
}
