/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health — DB + Redis */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness — touches no dependency */
        get: operations["live_healthz_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness — the go-live gate */
        get: operations["ready_healthz_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hooks/v1/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk user/organization mirror — Svix-signed (D-37: our DB is the record) */
        post: operations["clerk_webhook_hooks_v1_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hooks/v1/ingest/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Per-client lead intake → compliance-gated instant callback (FLOWS §4) */
        post: operations["ingest_hooks_v1_ingest__webhook_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client health overview (cross-tenant by design, audited surface) */
        get: operations["list_tenants_v1_admin_tenants_get"];
        put?: never;
        /** New-client wizard step 1 — org, retention defaults, agent draft, schema */
        post: operations["create_tenant_v1_admin_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants/{tenant_id}/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin a READ-ONLY view-as session (D-22) — audited, never acting-as */
        post: operations["start_impersonation_v1_admin_tenants__tenant_id__impersonate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants/{tenant_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Wizard step 8 — single-use 72h invite (token hashed at rest) */
        post: operations["invite_member_v1_admin_tenants__tenant_id__invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants/{tenant_id}/kb/{source_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approval gate (D-28: stays ours whichever RAG provider wins) */
        post: operations["approve_kb_v1_admin_tenants__tenant_id__kb__source_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants/{tenant_id}/kb/{source_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push to the engine KB and make this the active version
         * @description Rollback is republishing an earlier version (FLOWS §7).
         */
        post: operations["publish_kb_v1_admin_tenants__tenant_id__kb__source_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/tenants/{tenant_id}/kb/{source_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Kb */
        post: operations["reject_kb_v1_admin_tenants__tenant_id__kb__source_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create/update the agent on the engine and record its routing (admin only) */
        post: operations["publish_v1_agents__agent_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calls */
        get: operations["get_calls_v1_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Call detail — transcript is REDACTED by default (hard rule 5) */
        get: operations["get_call_v1_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/{call_id}/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Short-lived presigned link to OUR copy of the recording */
        get: operations["get_recording_v1_calls__call_id__recording_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/{call_id}/transcript/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unredacted transcript — role-checked AND audit-logged on every read */
        get: operations["get_raw_transcript_v1_calls__call_id__transcript_raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every campaign, newest first — a launched campaign must be findable later */
        get: operations["list_campaigns_v1_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_v1_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/numbers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Numbers this tenant may dial from, with their series (140/160/standard) */
        get: operations["list_numbers_v1_campaigns_numbers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DLT voice templates, so the launch gate's requirement is selectable */
        get: operations["list_templates_v1_campaigns_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live progress: dispatched / connected / failed / no-answer (FLOWS §5) */
        get: operations["progress_v1_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaign_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** CSV rows in — deduped, validated, malformed numbers counted not guessed */
        post: operations["add_contacts_v1_campaigns__campaign_id__contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaign_id}/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The compliance gate, then the DNC scrub, then running (hard rule 5) */
        post: operations["launch_v1_campaigns__campaign_id__launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaign_id}/launch-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Why the launch button is disabled, by name (SEC-COMP §3) */
        get: operations["launch_check_v1_campaigns__campaign_id__launch_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaign_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_v1_campaigns__campaign_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{campaign_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_v1_campaigns__campaign_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline numbers for the client dashboard */
        get: operations["get_dashboard_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an emailed invitation and create the membership (FLOWS §1 step 8)
         * @description The one authenticated route that does NOT require a membership — creating one is
         *     the point (see `current_identity`).
         *
         *     The burn is a CAS on `used_at IS NULL`, so two clicks on the same emailed link
         *     produce one membership rather than two.
         */
        post: operations["accept_invitation_v1_invitations_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kb/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_v1_kb_sources_get"];
        put?: never;
        /** Submit knowledge for review — chunked, previewable, NOT yet live */
        post: operations["submit_v1_kb_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kb/sources/{source_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Side-by-side preview of exactly what the agent would learn */
        get: operations["preview_source_v1_kb_sources__source_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leads */
        get: operations["get_leads_v1_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CSV export — full phone numbers, audit-logged */
        get: operations["export_leads_v1_leads_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead */
        get: operations["get_lead_v1_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Lead */
        patch: operations["patch_lead_v1_leads__lead_id__patch"];
        trace?: never;
    };
    "/v1/leads/{lead_id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch one AI call to this lead (D-21) — compliance-gated, idempotent */
        post: operations["call_lead_v1_leads__lead_id__call_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who am I, in which account, with what permissions */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recompute the audit hash chain and report the first broken link */
        get: operations["verify_audit_chain_v1_ops_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/outbox/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Flip dead-lettered outbox messages back to pending (audited) */
        post: operations["replay_outbox_v1_ops_outbox_replay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ops/platform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Platform */
        get: operations["read_platform_v1_ops_platform_get"];
        put?: never;
        /** Load-shed mode and the big red switch (step-up confirmed, audited) */
        post: operations["set_platform_v1_ops_platform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInviteIn */
        AcceptInviteIn: {
            /** Token */
            token: string;
        };
        /** AcceptInviteOut */
        AcceptInviteOut: {
            /** Role */
            role: string;
            /** Slug */
            slug: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** AddContactsIn */
        AddContactsIn: {
            /** Contacts */
            contacts: components["schemas"]["ContactIn"][];
        };
        /** AddContactsOut */
        AddContactsOut: {
            /** Added */
            added: number;
            /** Duplicate */
            duplicate: number;
            /** Malformed */
            malformed: number;
        };
        /** AgentOut */
        AgentOut: {
            /** Direction */
            direction: string;
            /** Disclosure Line */
            disclosure_line: string;
            /** Engine */
            engine: string;
            /**
             * Extraction Fields
             * @default []
             */
            extraction_fields: components["schemas"]["ExtractionField"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language Primary */
            language_primary: string;
            /** Name */
            name: string;
            /** Published */
            published: boolean;
            /** Status */
            status: string;
        };
        /** BlockerOut */
        BlockerOut: {
            /** Reason */
            reason: string;
            /** Rule */
            rule: string;
        };
        /** CallDetailOut */
        CallDetailOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Agent Name */
            agent_name?: string | null;
            /** Caller Masked */
            caller_masked?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "inbound" | "outbound";
            /** Disclosure Played */
            disclosure_played?: boolean | null;
            /** Duration S */
            duration_s?: number | null;
            /** Extraction */
            extraction?: {
                [key: string]: unknown;
            };
            /**
             * Extraction Valid
             * @default true
             */
            extraction_valid: boolean;
            /**
             * Has Recording
             * @default false
             */
            has_recording: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lead Id */
            lead_id?: string | null;
            /** Outcome Tag */
            outcome_tag?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
            /** Transcript */
            transcript?: components["schemas"]["TranscriptTurnOut"][];
        };
        /**
         * CallLeadIn
         * @description D-21: an owner may dispatch a single AI call from the Leads table, with an
         *     optional per-call note rendered into the agent's prompt.
         */
        CallLeadIn: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Context Note */
            context_note?: string | null;
        };
        /** CallLeadOut */
        CallLeadOut: {
            /** Blocked Reason */
            blocked_reason?: string | null;
            /** Blocked Rule */
            blocked_rule?: string | null;
            /** Call Handle */
            call_handle?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "blocked";
        };
        /** CallSummaryOut */
        CallSummaryOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Agent Name */
            agent_name?: string | null;
            /** Caller Masked */
            caller_masked?: string | null;
            /**
             * Direction
             * @enum {string}
             */
            direction: "inbound" | "outbound";
            /** Duration S */
            duration_s?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lead Id */
            lead_id?: string | null;
            /** Outcome Tag */
            outcome_tag?: string | null;
            /** Sentiment */
            sentiment?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
            /** Summary */
            summary?: string | null;
        };
        /** CampaignSummaryOut */
        CampaignSummaryOut: {
            /** Classification */
            classification: string;
            /** Connected */
            connected: number;
            /** Contacts */
            contacts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Launched At */
            launched_at: string | null;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** ChainVerifyOut */
        ChainVerifyOut: {
            /**
             * Checked
             * @default audit_log
             * @constant
             */
            checked: "audit_log";
            /** First Bad Entry Id */
            first_bad_entry_id?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** ChunkOut */
        ChunkOut: {
            /** Chars */
            chars: number;
            /** Content */
            content: string;
            /** Idx */
            idx: number;
        };
        /** ContactIn */
        ContactIn: {
            /** Custom */
            custom?: {
                [key: string]: string;
            };
            /** Name */
            name?: string | null;
            /** Phone */
            phone: string;
        };
        /** CreateCampaignIn */
        CreateCampaignIn: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /**
             * Classification
             * @enum {string}
             */
            classification: "promotional" | "transactional" | "service";
            /**
             * Concurrency
             * @default 3
             */
            concurrency: number;
            /** Dlt Template Id */
            dlt_template_id?: string | null;
            /** Name */
            name: string;
            /** Number Id */
            number_id?: string | null;
        };
        /** CreateCampaignOut */
        CreateCampaignOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** CreateOrgIn */
        CreateOrgIn: {
            /** Billing Email */
            billing_email?: string | null;
            /**
             * Language
             * @default te-IN
             * @enum {string}
             */
            language: "te-IN" | "hi-IN" | "en-IN";
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /**
             * Vertical Template
             * @default clinic
             * @enum {string}
             */
            vertical_template: "clinic" | "real_estate" | "insurance" | "education" | "custom";
        };
        /** CreateOrgOut */
        CreateOrgOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /**
             * Extraction Schema Id
             * Format: uuid
             */
            extraction_schema_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
        };
        /** DashboardOut */
        DashboardOut: {
            /**
             * After Hours Captured 7D
             * @default 0
             */
            after_hours_captured_7d: number;
            /** Avg Duration S */
            avg_duration_s?: number | null;
            /** Calls 7D */
            calls_7d: number;
            /** Calls Today */
            calls_today: number;
            /** Hot Leads Open */
            hot_leads_open: number;
            /** Leads New 7D */
            leads_new_7d: number;
            /** Minutes Used Month */
            minutes_used_month?: string | null;
            /** Outcome Split */
            outcome_split?: {
                [key: string]: number;
            };
            /** Sentiment Split */
            sentiment_split?: {
                [key: string]: number;
            };
        };
        /** ExtractionField */
        ExtractionField: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Enum Values */
            enum_values?: string[] | null;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Type
             * @enum {string}
             */
            type: "text" | "number" | "bool" | "enum" | "date";
        };
        /** InviteIn */
        InviteIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @default owner
             * @enum {string}
             */
            role: "owner" | "staff";
        };
        /** InviteOut */
        InviteOut: {
            /** Expires In Hours */
            expires_in_hours: number;
            /** Token */
            token: string;
        };
        /** LaunchCheckOut */
        LaunchCheckOut: {
            /** Blockers */
            blockers: components["schemas"]["BlockerOut"][];
            /** Ready */
            ready: boolean;
        };
        /** LaunchOut */
        LaunchOut: {
            /** Dialable */
            dialable: number;
            /** Dnc Scrubbed */
            dnc_scrubbed: number;
            /** Status */
            status: string;
        };
        /**
         * LeadListOut
         * @description The Leads table is schema-driven (TRD §7): the columns travel WITH the rows so
         *     the frontend never hard-codes a client's fields.
         */
        LeadListOut: {
            /** Columns */
            columns: components["schemas"]["ExtractionField"][];
            /** Items */
            items: components["schemas"]["LeadOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** LeadOut */
        LeadOut: {
            /** Call Count */
            call_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Repeat Caller */
            is_repeat_caller: boolean;
            /** Last Call Id */
            last_call_id?: string | null;
            /** Name */
            name?: string | null;
            /** Phone Masked */
            phone_masked: string;
            /** Schema Version */
            schema_version?: number | null;
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "interested" | "hot" | "won" | "lost";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LeadUpdateIn */
        LeadUpdateIn: {
            /** Name */
            name?: string | null;
            /** Status */
            status?: ("new" | "contacted" | "interested" | "hot" | "won" | "lost") | null;
        };
        /** MeOut */
        MeOut: {
            /** Impersonating */
            impersonating: boolean;
            organization?: components["schemas"]["OrganizationOut"] | null;
            /** Permissions */
            permissions: string[];
            /** Realm */
            realm: string;
            /** Role */
            role: string | null;
            /** User Id */
            user_id: string | null;
        };
        /** NumberOut */
        NumberOut: {
            /** Dlt Status */
            dlt_status: string;
            /** E164 */
            e164: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Series */
            series: string;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Vertical Template */
            vertical_template?: string | null;
        };
        /** PlatformStateIn */
        PlatformStateIn: {
            /** Load Shed Mode */
            load_shed_mode?: ("normal" | "reduced" | "emergency" | "maintenance") | null;
            /** Outbound Halted */
            outbound_halted?: boolean | null;
            /** Reason */
            reason: string;
        };
        /** PlatformStateOut */
        PlatformStateOut: {
            /** Load Shed Mode */
            load_shed_mode: string;
            /** Outbound Halted */
            outbound_halted: boolean;
        };
        /** ProgressOut */
        ProgressOut: {
            /** Concurrency */
            concurrency: number;
            /** Contacts */
            contacts: {
                [key: string]: number;
            };
            /** Launched At */
            launched_at: string | null;
            /** Status */
            status: string;
            /** Total */
            total: number;
        };
        /** RecordingLinkOut */
        RecordingLinkOut: {
            /** Expires In S */
            expires_in_s: number;
            /** Url */
            url: string;
        };
        /** RejectIn */
        RejectIn: {
            /** Reason */
            reason: string;
        };
        /** ReplayOut */
        ReplayOut: {
            /** Replayed */
            replayed: number;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Chunks */
            chunks: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Published At */
            published_at: string | null;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** SubmitIn */
        SubmitIn: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Body */
            body: string;
            /**
             * Kind
             * @default text
             * @enum {string}
             */
            kind: "text" | "url" | "file";
            /** Name */
            name: string;
            /** Uri */
            uri?: string | null;
        };
        /** SubmitOut */
        SubmitOut: {
            /** Chunks */
            chunks: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Body */
            body: string;
            /** Classification */
            classification: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** TenantSummary */
        TenantSummary: {
            /** Calls 7D */
            calls_7d: number;
            /** Capped */
            capped: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Call At */
            last_call_at: string | null;
            /** Leads */
            leads: number;
            /** Live Agents */
            live_agents: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Vertical Template */
            vertical_template: string | null;
        };
        /** TranscriptTurnOut */
        TranscriptTurnOut: {
            /** Idx */
            idx: number;
            /** Lang */
            lang?: string | null;
            /**
             * Redacted
             * @default true
             */
            redacted: boolean;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "agent" | "caller";
            /** Start Ms */
            start_ms?: number | null;
            /** Text */
            text: string;
        };
        /** PublishOut */
        apps__api__admin__routes__PublishOut: {
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Status */
            status: string;
            /** Version */
            version: number;
        };
        /** PublishOut */
        apps__api__agents__routes__PublishOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Engine Agent Ref */
            engine_agent_ref: string;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    live_healthz_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    ready_healthz_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    clerk_webhook_hooks_v1_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    ingest_hooks_v1_ingest__webhook_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_tenants_v1_admin_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSummary"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    create_tenant_v1_admin_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    start_impersonation_v1_admin_tenants__tenant_id__impersonate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    invite_member_v1_admin_tenants__tenant_id__invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    approve_kb_v1_admin_tenants__tenant_id__kb__source_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    publish_kb_v1_admin_tenants__tenant_id__kb__source_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apps__api__admin__routes__PublishOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    reject_kb_v1_admin_tenants__tenant_id__kb__source_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_agents_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_agent_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    publish_v1_agents__agent_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apps__api__agents__routes__PublishOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_calls_v1_calls_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallSummaryOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_call_v1_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallDetailOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_recording_v1_calls__call_id__recording_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingLinkOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_raw_transcript_v1_calls__call_id__transcript_raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallDetailOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_campaigns_v1_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSummaryOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    create_campaign_v1_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCampaignOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_numbers_v1_campaigns_numbers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NumberOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_templates_v1_campaigns_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    progress_v1_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    add_contacts_v1_campaigns__campaign_id__contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddContactsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddContactsOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    launch_v1_campaigns__campaign_id__launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    launch_check_v1_campaigns__campaign_id__launch_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchCheckOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    pause_v1_campaigns__campaign_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    resume_v1_campaigns__campaign_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_dashboard_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    accept_invitation_v1_invitations_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInviteOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    list_sources_v1_kb_sources_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    submit_v1_kb_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    preview_source_v1_kb_sources__source_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkOut"][];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_leads_v1_leads_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: string | null;
                search?: string | null;
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadListOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    export_leads_v1_leads_export_csv_get: {
        parameters: {
            query?: {
                agent_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    get_lead_v1_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    patch_lead_v1_leads__lead_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    call_lead_v1_leads__lead_id__call_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallLeadIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallLeadOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    verify_audit_chain_v1_ops_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainVerifyOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    replay_outbox_v1_ops_outbox_replay_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    read_platform_v1_ops_platform_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStateOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    set_platform_v1_ops_platform_post: {
        parameters: {
            query?: never;
            header?: {
                "x-confirm-action"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformStateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformStateOut"];
                };
            };
            /** @description RFC-9457 problem+json */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
}
