"use client";

/**
 * Client-realm structured call-script builder hooks — `/v1/agents/{id}/script/...`.
 *
 * This is the exception's exception. `agents.ts` is read-only but for `useSetDisclosure`,
 * on D-21's ground that a script change routes through us. The founder's APPROVED DECISION
 * makes the STRUCTURED builder the primary client authoring surface, so these mutation
 * hooks exist — reconciled with D-21 rather than overriding it: every save STAGES (the
 * server's slow lane), and nothing reaches a live call until an explicit `useApplyScript`.
 * See `apps/api/agents/script_routes.py` for the flagged conflict and its resolution.
 *
 * ⚠ TYPES ARE HAND-DECLARED, NOT ALIASED FROM `./schema`, and this is a KNOWN DEVIATION
 * from the generated-client doctrine. The OpenAPI snapshot and the TS schema are
 * regenerated by `pnpm gen:api` against a RUNNING API; these endpoints are new, so until
 * that is run they are absent from `components["schemas"]`. The shapes below mirror the
 * Pydantic models in `script_routes.py` exactly; fold them into the generated aliases the
 * next time `gen:api` runs (the same staleness `agents/routes.py` already flags for the
 * publish path). Keeping them typed here rather than `any` means the builder still gets
 * real checking in the meantime.
 */

import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationResult,
  type UseQueryResult,
} from "@tanstack/react-query";

import { agentKeys } from "./agents";
import { apiRequest, type Session } from "./client";
import { publishingKeys } from "./publishing";

/** One `{{ }}` merge field the author declared. Mirrors `ScriptVariable`. */
export interface ScriptVariable {
  key: string;
  label: string;
  example: string;
}

/** One ordered task-flow instruction. Mirrors `ScriptStep`. */
export interface ScriptStep {
  instruction: string;
}

/** One FAQ question/answer pair. Mirrors `FaqEntry`. */
export interface FaqEntry {
  question: string;
  answer: string;
}

/**
 * A whole agent script, structured — or a raw escape hatch. Mirrors `CallScript`.
 *
 * `raw_override` null = structured mode (the fields below are used); a string = raw mode
 * (the fields are ignored and this text is the body verbatim). The server refuses both at
 * once, so the UI clears one side when switching modes.
 */
export interface CallScript {
  opening_line: string;
  steps: ScriptStep[];
  faqs: FaqEntry[];
  faq_fallback: string;
  end_call_extra_rules: string[];
  variables: ScriptVariable[];
  raw_override: string | null;
}

/** The empty structured script a brand-new agent opens on. */
export const EMPTY_SCRIPT: CallScript = {
  opening_line: "",
  steps: [],
  faqs: [],
  faq_fallback: "నాకు ఆ వివరం ఖచ్చితంగా తెలియదు — మా టీమ్ మీకు తిరిగి కాల్ చేసి చెబుతుంది.",
  end_call_extra_rules: [],
  variables: [],
  raw_override: null,
};

export interface ScriptOut {
  script: CallScript;
  version: number | null;
  is_freeform: boolean;
  has_pending: boolean;
  standard_variables: { key: string; label: string }[];
}

interface SaveScriptIn {
  script: CallScript;
  notes?: string | null;
}

interface SaveScriptOut {
  version: number;
  staged: boolean;
}

interface PreviewOut {
  compiled: string;
}

interface AssistIn {
  description: string;
}

export interface AssistOut {
  script: CallScript;
  disclosure: string | null;
  metered: boolean;
}

interface ApplyIn {
  expected_version?: number | null;
}

interface ApplyOut {
  applied: boolean;
  live_version: number;
  engine_synced: boolean;
}

interface UndoOut {
  undone: boolean;
  discarded_version: number | null;
  live_version: number | null;
}

export const scriptKeys = {
  one: (org: string, agentId: string) => ["script", org, agentId] as const,
};

const base = (agentId: string) => `/v1/agents/${agentId}/script`;

/** The agent's DRAFT script for the builder to edit. */
export function useScript(session: Session, agentId: string): UseQueryResult<ScriptOut, Error> {
  return useQuery({
    queryKey: scriptKeys.one(session.orgSlug, agentId),
    queryFn: () => apiRequest<ScriptOut>(session, base(agentId)),
  });
}

/** Save the structured script as a new version (staged on a live agent). */
export function useSaveScript(
  session: Session,
  agentId: string,
): UseMutationResult<SaveScriptOut, Error, SaveScriptIn> {
  const client = useQueryClient();
  return useMutation({
    mutationFn: (payload: SaveScriptIn) =>
      apiRequest<SaveScriptOut>(session, base(agentId), { method: "PUT", body: payload }),
    onSuccess: () =>
      Promise.all([
        client.invalidateQueries({ queryKey: scriptKeys.one(session.orgSlug, agentId) }),
        client.invalidateQueries({ queryKey: agentKeys.one(session.orgSlug, agentId) }),
        client.invalidateQueries({ queryKey: publishingKeys.pending(session.orgSlug, agentId) }),
      ]),
  });
}

/**
 * Compile a (possibly unsaved) script into the exact engine prompt. A mutation, not a
 * query: it takes the current editor state as input rather than reading the server's copy,
 * so "view compiled prompt" reflects unsaved edits.
 */
export function usePreviewScript(
  session: Session,
  agentId: string,
): UseMutationResult<PreviewOut, Error, CallScript> {
  return useMutation({
    mutationFn: (script: CallScript) =>
      apiRequest<PreviewOut>(session, `${base(agentId)}/preview`, {
        method: "POST",
        body: { script },
      }),
  });
}

/** Draft a script from a plain-language business description (the AI writing assist). */
export function useAssistScript(
  session: Session,
  agentId: string,
): UseMutationResult<AssistOut, Error, AssistIn> {
  return useMutation({
    mutationFn: (payload: AssistIn) =>
      apiRequest<AssistOut>(session, `${base(agentId)}/assist`, {
        method: "POST",
        body: payload,
      }),
  });
}

/** Apply the staged script to live calls (CAS on the version the author reviewed). */
export function useApplyScript(
  session: Session,
  agentId: string,
): UseMutationResult<ApplyOut, Error, ApplyIn> {
  const client = useQueryClient();
  return useMutation({
    mutationFn: (payload: ApplyIn) =>
      apiRequest<ApplyOut>(session, `${base(agentId)}/apply`, { method: "POST", body: payload }),
    onSuccess: () =>
      Promise.all([
        client.invalidateQueries({ queryKey: scriptKeys.one(session.orgSlug, agentId) }),
        client.invalidateQueries({ queryKey: agentKeys.one(session.orgSlug, agentId) }),
        client.invalidateQueries({ queryKey: publishingKeys.pending(session.orgSlug, agentId) }),
      ]),
  });
}

/** Discard the staged script; the draft returns to what callers hear. */
export function useUndoScript(
  session: Session,
  agentId: string,
): UseMutationResult<UndoOut, Error, void> {
  const client = useQueryClient();
  return useMutation({
    mutationFn: () => apiRequest<UndoOut>(session, `${base(agentId)}/undo`, { method: "POST" }),
    onSuccess: () =>
      Promise.all([
        client.invalidateQueries({ queryKey: scriptKeys.one(session.orgSlug, agentId) }),
        client.invalidateQueries({ queryKey: agentKeys.one(session.orgSlug, agentId) }),
        client.invalidateQueries({ queryKey: publishingKeys.pending(session.orgSlug, agentId) }),
      ]),
  });
}
