"""`scripts/dev.py` — the supervisor that prints auth codes and swallows everything else.

Two things are worth guarding and they are different in kind.

**The commands must not drift from `make dev`.** This script exists because the Makefile
recipe is a POSIX `&` pipeline that does not run on Windows, so the same four services are
now spelled in two places. Two spellings of one fact is the defect class D-103/D-105 exist
for, and the failure would be quiet: a developer's stack silently missing the flag that
makes voice-runtime importable, or reloading on a different port than CI and the runbooks
name. So the sets are compared rather than trusted.

**The extraction must survive the message it reads.** The code is pulled out of a body
`apps/workers/auth_email._body` writes, by a regex anchored on that sentence. If either
side is reworded the script goes quiet — the worst failure mode for this tool, because
quiet is also what success looks like. So the patterns are exercised against the REAL
bodies, generated by the real function, for every kind that carries a secret.
"""

from __future__ import annotations

import io
import json
import os
import re
import signal
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import pytest
from apps.workers.auth_email import _SUBJECTS, _body
from scripts import dev
from scripts.dev import _CODE_RE, _LINK_RE, Service, services

REPO_ROOT = Path(__file__).resolve().parent.parent

#: The kinds whose body carries a six-digit code, and the kinds whose body carries a
#: single-use link. Derived from `_SUBJECTS` below rather than retyped, so a new kind
#: fails this file instead of being silently unprinted by the supervisor.
_OTP_KINDS = {"otp_login_challenge", "otp_step_up", "otp_email_verify"}
_LINK_KINDS = {"password_reset", "invite_password", "admin_bootstrap"}


def _make_dev_recipe() -> str:
    """The body of the Makefile's `dev:` target."""
    text = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    match = re.search(r"^dev:\n((?:\t.*\n)+)", text, re.M)
    assert match, "no `dev:` target in the Makefile — this guard is looking at nothing"
    return match.group(1)


def test_the_supervisor_starts_what_make_dev_starts() -> None:
    """Same four services, same ports, same flags.

    Compared as SUBSTRINGS of the recipe rather than by parsing shell, because the recipe
    is a `&`-chained pipeline and a parser for it would be the second fragile thing here.
    What matters is that every distinguishing token this script passes — the app path, the
    port, `--app-dir` — appears in the Makefile's spelling of the same service.
    """
    recipe = _make_dev_recipe()
    for service in services():
        # `pnpm` resolves to an absolute `pnpm.cmd` on Windows; the ARGUMENTS are the part
        # that has to agree, and the executable is this script's platform problem.
        for token in service.command[1:]:
            assert token in recipe, (
                f"`scripts/dev.py` starts {service.name} with {token!r} and the Makefile's "
                f"`dev:` target does not mention it — the two have drifted"
            )


def test_every_service_make_dev_starts_is_supervised() -> None:
    """The other direction: a fifth service added to the Makefile must not be missed.

    Counted by `&`-separated commands, which is exactly how the recipe expresses "and
    also run this". A supervisor that starts three of four services is worse than one that
    starts none, because the missing one fails later and somewhere else.
    """
    recipe = _make_dev_recipe()
    started = [part for part in re.split(r"&\s*\\?\n?", recipe) if part.strip()]
    assert len(started) == len(services()), (
        f"the Makefile's `dev:` runs {len(started)} commands and scripts/dev.py "
        f"supervises {len(services())}"
    )


@pytest.mark.parametrize("kind", sorted(_OTP_KINDS))
def test_the_code_is_found_in_the_body_that_actually_gets_sent(kind: str) -> None:
    """Against `_body`'s real output, never a hand-copied sample.

    A fixture string here would keep passing after the template was reworded, which is the
    one way this guard could fail to guard anything.
    """
    found = _CODE_RE.search(_body(kind, "admin", "483921"))
    assert found is not None, f"no code found in a {kind} body — the supervisor prints nothing"
    assert found.group(1) == "483921"


@pytest.mark.parametrize("kind", sorted(_LINK_KINDS))
def test_the_single_use_link_is_found_too(kind: str) -> None:
    found = _LINK_RE.search(_body(kind, "admin", "tok_abc123"))
    assert found is not None, f"no link found in a {kind} body"
    assert found.group(1).endswith("tok_abc123")


def test_every_kind_that_carries_a_secret_is_one_of_the_two_shapes() -> None:
    """The set this script knows how to read, pinned to the set that exists.

    A NEW kind added to `_SUBJECTS` lands here rather than being delivered to a terminal
    that prints nothing for it — which is exactly what `admin_bootstrap` did when the
    console gained `POST /v1/admin/operators`: a single-use operator setup link that
    `make dev-otp` would have swallowed, on the one flow where the link IS the only copy
    of the secret.
    """
    assert set(_SUBJECTS) == _OTP_KINDS | _LINK_KINDS


def test_a_six_digit_number_that_is_not_a_code_is_not_printed_as_one() -> None:
    """The negative control, and the reason `_CODE_RE` is anchored on the sentence.

    `\\d{6}` anywhere in a body would turn a request id, a rupee amount or a year range
    into something a developer types into an OTP field and then blames the API for
    refusing. The pattern requires the words the template actually uses.
    """
    assert _CODE_RE.search("Your invoice 483921 is ready. Reference 100200.") is None
    assert _CODE_RE.search("Nothing here is a code at all.") is None


# ── voice-runtime's import path under the reloader ────────────────────────────────────

_PROBE_APP = """
import json, os, sys
try:
    import apps.api.core  # noqa: F401  -- what voice-runtime's main.py imports first
    imported = True
except ModuleNotFoundError:
    imported = False
with open(os.environ["PROBE_OUT"], "w", encoding="utf-8") as out:
    json.dump({"sys_path": sys.path, "imported": imported}, out)

async def app(scope, receive, send):
    pass
"""


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def test_the_reloaded_voice_runtime_process_can_import_the_repo(tmp_path: Path) -> None:
    """The server process uvicorn's reloader spawns can `import apps.api`.

    Run for real rather than asserted from the command's spelling: the defect was that
    `uvicorn` the console script starts with its own `Scripts/`/`bin/` directory at
    `sys.path[0]` and `--app-dir` adds only `apps/voice-runtime`, so the repo root was
    never on the path and `main.py:29` failed in every server process. The reloader's
    server is a `multiprocessing` spawn child that inherits the reloader's `sys.path`;
    each restart builds the next one the same way (`get_subprocess`), so the first one
    is the one to measure.
    """
    (vr,) = [s for s in services() if s.name == "voice-runtime"]
    uv_run, interpreter = vr.command[:2], vr.command[2]
    assert uv_run == ["uv", "run"] and interpreter == "python", vr.command
    args = vr.command[3:]
    assert args[:2] == ["-m", "uvicorn"], "voice-runtime must run uvicorn as a module"
    # Swap only what the probe needs: its own app, its own directory, a free port.
    args = [a for a in args if a not in ("main:app",)]
    app_dir_at = args.index("--app-dir")
    args[app_dir_at + 1] = str(tmp_path)
    port_at = args.index("--port")
    args[port_at + 1] = str(_free_port())
    (tmp_path / "probe.py").write_text(_PROBE_APP, encoding="utf-8")
    out = tmp_path / "probe.json"

    # Its own process group / session, so the tree can be killed whole afterwards.
    if sys.platform == "win32":
        group: dict[str, Any] = {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    else:
        group = {"start_new_session": True}
    proc = subprocess.Popen(
        [sys.executable, *args, "probe:app", "--reload-dir", str(tmp_path)],
        cwd=REPO_ROOT,
        env={**os.environ, "PROBE_OUT": str(out)},
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        **group,
    )
    try:
        deadline = time.monotonic() + 60
        while not out.exists() and time.monotonic() < deadline and proc.poll() is None:
            time.sleep(0.2)
        time.sleep(0.2)  # let the write finish
        assert out.exists(), "the reloader never started a server process"
        seen = json.loads(out.read_text(encoding="utf-8"))
    finally:
        if sys.platform == "win32":
            subprocess.run(
                ["taskkill", "/PID", str(proc.pid), "/T", "/F"], capture_output=True, check=False
            )
        else:
            os.killpg(proc.pid, signal.SIGKILL)
        proc.wait(timeout=10)

    assert seen["imported"], f"`import apps.api` failed in the server process: {seen['sys_path']}"
    roots = {Path(p).resolve() for p in seen["sys_path"] if p}
    assert REPO_ROOT in roots


# ── a reloader's Ctrl-C must not stop the stack ───────────────────────────────────────


def test_the_reload_mark_is_recorded_whichever_mode_is_on() -> None:
    dev._last_reload.clear()
    line = "WARNING:  WatchFiles detected changes in 'apps/api/x.py'. Reloading...\n"
    dev._pump(Service("api", [], None), io.StringIO(line), verbose=False, tail=[])
    assert dev._last_reload and dev._last_reload[-1][1] == "api"


@pytest.mark.parametrize(
    ("offset", "echo"),
    [(-dev._ECHO_BEFORE_S - 0.1, False), (-1.0, True), (0.0, True), (0.5, True), (1.5, False)],
)
def test_only_a_reload_close_to_the_signal_explains_it(offset: float, echo: bool) -> None:
    assert dev._is_reload_echo(100.0, 100.0 + offset) is echo


def test_a_ctrl_c_with_a_reload_beside_it_is_the_reloaders(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(os, "name", "nt")
    now = time.monotonic()
    monkeypatch.setattr(dev, "_last_reload", [(now - 0.5, "voice-runtime")])
    assert dev._reload_echo(now) == "voice-runtime"


def test_a_ctrl_c_with_no_reload_beside_it_is_a_person(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(os, "name", "nt")
    monkeypatch.setattr(dev, "_ECHO_AFTER_S", 0.1)
    monkeypatch.setattr(dev, "_last_reload", [(time.monotonic() - 60, "api")])
    assert dev._reload_echo(time.monotonic()) is None


def test_off_windows_every_ctrl_c_is_a_person(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(os, "name", "posix")
    now = time.monotonic()
    monkeypatch.setattr(dev, "_last_reload", [(now, "api")])
    assert dev._reload_echo(now) is None
