"""`scripts/dev.py` — the supervisor that prints auth codes and swallows everything else.

Two things are worth guarding and they are different in kind.

**The commands must not drift from `make dev`.** This script exists because the Makefile
recipe is a POSIX `&` pipeline that does not run on Windows, so the same four services are
now spelled in two places. Two spellings of one fact is the defect class D-103/D-105 exist
for, and the failure would be quiet: a developer's stack silently missing the flag that
makes voice-runtime importable, or reloading on a different port than CI and the runbooks
name. So the sets are compared rather than trusted.

**The extraction must survive the message it reads.** The code is pulled out of a body
`apps/workers/auth_email._body` writes, by a regex anchored on that sentence. If either
side is reworded the script goes quiet — the worst failure mode for this tool, because
quiet is also what success looks like. So the patterns are exercised against the REAL
bodies, generated by the real function, for every kind that carries a secret.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from apps.workers.auth_email import _SUBJECTS, _body
from scripts.dev import _CODE_RE, _LINK_RE, services

REPO_ROOT = Path(__file__).resolve().parent.parent

#: The kinds whose body carries a six-digit code, and the kinds whose body carries a
#: single-use link. Derived from `_SUBJECTS` below rather than retyped, so a new kind
#: fails this file instead of being silently unprinted by the supervisor.
_OTP_KINDS = {"otp_login_challenge", "otp_step_up", "otp_email_verify"}
_LINK_KINDS = {"password_reset", "invite_password", "admin_bootstrap"}


def _make_dev_recipe() -> str:
    """The body of the Makefile's `dev:` target."""
    text = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    match = re.search(r"^dev:\n((?:\t.*\n)+)", text, re.M)
    assert match, "no `dev:` target in the Makefile — this guard is looking at nothing"
    return match.group(1)


def test_the_supervisor_starts_what_make_dev_starts() -> None:
    """Same four services, same ports, same flags.

    Compared as SUBSTRINGS of the recipe rather than by parsing shell, because the recipe
    is a `&`-chained pipeline and a parser for it would be the second fragile thing here.
    What matters is that every distinguishing token this script passes — the app path, the
    port, `--app-dir` — appears in the Makefile's spelling of the same service.
    """
    recipe = _make_dev_recipe()
    for service in services():
        # `pnpm` resolves to an absolute `pnpm.cmd` on Windows; the ARGUMENTS are the part
        # that has to agree, and the executable is this script's platform problem.
        for token in service.command[1:]:
            assert token in recipe, (
                f"`scripts/dev.py` starts {service.name} with {token!r} and the Makefile's "
                f"`dev:` target does not mention it — the two have drifted"
            )


def test_every_service_make_dev_starts_is_supervised() -> None:
    """The other direction: a fifth service added to the Makefile must not be missed.

    Counted by `&`-separated commands, which is exactly how the recipe expresses "and
    also run this". A supervisor that starts three of four services is worse than one that
    starts none, because the missing one fails later and somewhere else.
    """
    recipe = _make_dev_recipe()
    started = [part for part in re.split(r"&\s*\\?\n?", recipe) if part.strip()]
    assert len(started) == len(services()), (
        f"the Makefile's `dev:` runs {len(started)} commands and scripts/dev.py "
        f"supervises {len(services())}"
    )


@pytest.mark.parametrize("kind", sorted(_OTP_KINDS))
def test_the_code_is_found_in_the_body_that_actually_gets_sent(kind: str) -> None:
    """Against `_body`'s real output, never a hand-copied sample.

    A fixture string here would keep passing after the template was reworded, which is the
    one way this guard could fail to guard anything.
    """
    found = _CODE_RE.search(_body(kind, "admin", "483921"))
    assert found is not None, f"no code found in a {kind} body — the supervisor prints nothing"
    assert found.group(1) == "483921"


@pytest.mark.parametrize("kind", sorted(_LINK_KINDS))
def test_the_single_use_link_is_found_too(kind: str) -> None:
    found = _LINK_RE.search(_body(kind, "admin", "tok_abc123"))
    assert found is not None, f"no link found in a {kind} body"
    assert found.group(1).endswith("tok_abc123")


def test_every_kind_that_carries_a_secret_is_one_of_the_two_shapes() -> None:
    """The set this script knows how to read, pinned to the set that exists.

    A NEW kind added to `_SUBJECTS` lands here rather than being delivered to a terminal
    that prints nothing for it — which is exactly what `admin_bootstrap` did when the
    console gained `POST /v1/admin/operators`: a single-use operator setup link that
    `make dev-otp` would have swallowed, on the one flow where the link IS the only copy
    of the secret.
    """
    assert set(_SUBJECTS) == _OTP_KINDS | _LINK_KINDS


def test_a_six_digit_number_that_is_not_a_code_is_not_printed_as_one() -> None:
    """The negative control, and the reason `_CODE_RE` is anchored on the sentence.

    `\\d{6}` anywhere in a body would turn a request id, a rupee amount or a year range
    into something a developer types into an OTP field and then blames the API for
    refusing. The pattern requires the words the template actually uses.
    """
    assert _CODE_RE.search("Your invoice 483921 is ready. Reference 100200.") is None
    assert _CODE_RE.search("Nothing here is a code at all.") is None
