"""db core with rls

Revision ID: 05bba2f3c19c
Revises: 
Create Date: 2026-07-27 11:54:14.290970

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '05bba2f3c19c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.String(), server_default='operator', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('superadmin', 'operator')", name=op.f('ck_admin_users_role_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('clerk_user_id', name=op.f('uq_admin_users_clerk_user_id'))
    )
    op.create_table('idempotency_records',
    sa.Column('scope_key', sa.Text(), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='processing', nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name=op.f('ck_idempotency_records_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('scope_key', 'route', 'method', 'idempotency_key', name=op.f('uq_idempotency_records_scope_key_route_method_idempotency_key'))
    )
    op.create_index('ix_idempotency_expiry', 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='prospect', nullable=False),
    sa.Column('vertical_template', sa.Text(), nullable=True),
    sa.Column('billing_email', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]{3,40}$'", name=op.f('ck_organizations_slug_shape')),
    sa.CheckConstraint("status IN ('prospect', 'onboarding', 'active', 'suspended', 'churned')", name=op.f('ck_organizations_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('outbox_messages',
    sa.Column('queue', sa.Text(), nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'published', 'failed')", name=op.f('ck_outbox_messages_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages'))
    )
    op.create_index('ix_outbox_pending', 'outbox_messages', ['status', 'created_at'], unique=False)
    op.create_table('reserved_slugs',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_reserved_slugs'))
    )
    op.create_table('users',
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('clerk_user_id', name=op.f('uq_users_clerk_user_id'))
    )
    op.create_table('webhook_deliveries',
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('payload_ref', sa.Text(), nullable=True),
    sa.Column('first_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("direction IN ('in', 'out')", name=op.f('ck_webhook_deliveries_direction_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries'))
    )
    op.create_table('webhook_inbox_events',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('event_key', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='processing', nullable=False),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'enqueued', 'processed', 'failed')", name=op.f('ck_webhook_inbox_events_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_inbox_events')),
    sa.UniqueConstraint('provider', 'event_key', name=op.f('uq_webhook_inbox_events_provider_event_key'))
    )
    op.create_table('agents',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('language_primary', sa.Text(), server_default='te-IN', nullable=False),
    sa.Column('languages_extra', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('stt_provider', sa.Text(), nullable=True),
    sa.Column('stt_model', sa.Text(), nullable=True),
    sa.Column('tts_provider', sa.Text(), nullable=True),
    sa.Column('tts_voice', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('system_prompt_id', sa.UUID(), nullable=True),
    sa.Column('extraction_schema_id', sa.UUID(), nullable=True),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disclosure_line', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('engine', sa.String(), server_default='fake', nullable=False),
    sa.Column('engine_agent_ref', sa.Text(), nullable=True),
    sa.Column('engine_staging_ref', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound', 'both')", name=op.f('ck_agents_direction_enum')),
    sa.CheckConstraint("engine IN ('fake', 'bolna')", name=op.f('ck_agents_engine_enum')),
    sa.CheckConstraint("status IN ('draft', 'live', 'paused')", name=op.f('ck_agents_status_enum')),
    sa.CheckConstraint('length(disclosure_line) > 0', name=op.f('ck_agents_disclosure_nonempty')),
    sa.ForeignKeyConstraint(['extraction_schema_id'], ['extraction_schemas.id'], name=op.f('fk_agents_extraction_schema_id_extraction_schemas'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['system_prompt_id'], ['prompt_versions.id'], name=op.f('fk_agents_system_prompt_id_prompt_versions'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_agents_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Text(), nullable=True),
    sa.Column('object_id', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=True),
    sa.Column('entry_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("actor_type IN ('admin', 'user', 'system')", name=op.f('ck_audit_log_actor_enum')),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_audit_log_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('deletion_requests',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_deletion_requests_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deletion_requests'))
    )
    op.create_index(op.f('ix_deletion_requests_tenant_id'), 'deletion_requests', ['tenant_id'], unique=False)
    op.create_table('invitations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now() + make_interval(0, 0, 0, 0, 72)'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff')", name=op.f('ck_invitations_role_enum')),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_invitations_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    op.create_index(op.f('ix_invitations_tenant_id'), 'invitations', ['tenant_id'], unique=False)
    op.create_table('memberships',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff')", name=op.f('ck_memberships_role_enum')),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_memberships_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('tenant_id', 'user_id', name=op.f('uq_memberships_tenant_id_user_id'))
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('outbound_webhooks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('events', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('webhook', 'google_sheets')", name=op.f('ck_outbound_webhooks_kind_enum')),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_outbound_webhooks_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_webhooks'))
    )
    op.create_index(op.f('ix_outbound_webhooks_tenant_id'), 'outbound_webhooks', ['tenant_id'], unique=False)
    op.create_table('plans',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('setup_fee', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('included_min', sa.Integer(), nullable=True),
    sa.Column('overage_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('hard_cap_min', sa.Integer(), nullable=True),
    sa.Column('hard_cap_spend', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('concurrency_ceiling', sa.Integer(), server_default='10', nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_plans_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('data_category', sa.String(), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), server_default='delete', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action IN ('delete', 'anonymize')", name=op.f('ck_retention_policies_action_enum')),
    sa.CheckConstraint("data_category != 'recording' OR ttl_days >= 90", name=op.f('ck_retention_policies_recording_ttl_floor')),
    sa.CheckConstraint("data_category IN ('recording', 'transcript', 'lead', 'consent_log')", name=op.f('ck_retention_policies_category_enum')),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_retention_policies_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies'))
    )
    op.create_index(op.f('ix_retention_policies_tenant_id'), 'retention_policies', ['tenant_id'], unique=False)
    op.create_table('spend_state',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Text(), nullable=False),
    sa.Column('minutes_used', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('spend_used', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('capped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_spend_state_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_spend_state'))
    )
    op.create_table('extraction_schemas',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_extraction_schemas_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_extraction_schemas_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_schemas')),
    sa.UniqueConstraint('agent_id', 'version', name=op.f('uq_extraction_schemas_agent_id_version'))
    )
    op.create_index(op.f('ix_extraction_schemas_agent_id'), 'extraction_schemas', ['agent_id'], unique=False)
    op.create_index(op.f('ix_extraction_schemas_tenant_id'), 'extraction_schemas', ['tenant_id'], unique=False)
    op.create_table('inbound_webhooks',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('meta_lead_ads', 'website_form', 'zoho', 'sheets', 'custom')", name=op.f('ck_inbound_webhooks_source_enum')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_inbound_webhooks_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_inbound_webhooks_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_webhooks'))
    )
    op.create_index(op.f('ix_inbound_webhooks_tenant_id'), 'inbound_webhooks', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='new', nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('first_call_id', sa.UUID(), nullable=True),
    sa.Column('last_call_id', sa.UUID(), nullable=True),
    sa.Column('call_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_repeat_caller', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('inbound_call', 'webhook', 'campaign', 'manual')", name=op.f('ck_leads_source_enum')),
    sa.CheckConstraint("status IN ('new', 'contacted', 'interested', 'hot', 'won', 'lost')", name=op.f('ck_leads_status_enum')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_leads_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_leads_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_leads_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('tenant_id', 'phone_e164', 'agent_id', name=op.f('uq_leads_tenant_id_phone_e164_agent_id'))
    )
    op.create_index(op.f('ix_leads_agent_id'), 'leads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('e164', sa.Text(), nullable=False),
    sa.Column('series', sa.String(), server_default='standard', nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('engine_number_ref', sa.Text(), nullable=True),
    sa.Column('dlt_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dlt_status IN ('pending', 'registered', 'blocked')", name=op.f('ck_phone_numbers_dlt_status_enum')),
    sa.CheckConstraint("series IN ('140', '160', 'standard')", name=op.f('ck_phone_numbers_series_enum')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_phone_numbers_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_phone_numbers_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers')),
    sa.UniqueConstraint('e164', name=op.f('uq_phone_numbers_e164'))
    )
    op.create_index(op.f('ix_phone_numbers_tenant_id'), 'phone_numbers', ['tenant_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('compiled_t0_context', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_prompt_versions_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_prompt_versions_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('agent_id', 'version', name=op.f('uq_prompt_versions_agent_id_version'))
    )
    op.create_index(op.f('ix_prompt_versions_agent_id'), 'prompt_versions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_tenant_id'), 'prompt_versions', ['tenant_id'], unique=False)
    op.create_table('calls',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('engine_call_id', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('from_e164', sa.Text(), nullable=True),
    sa.Column('to_e164', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('disclosure_played', sa.Boolean(), nullable=True),
    sa.Column('consent_recording', sa.String(), nullable=True),
    sa.Column('outcome_tag', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('latency', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engine_payload_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("consent_recording IS NULL OR consent_recording IN ('granted', 'declined', 'na')", name=op.f('ck_calls_consent_enum')),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name=op.f('ck_calls_direction_enum')),
    sa.CheckConstraint("outcome_tag IS NULL OR outcome_tag IN ('resolved', 'needs_follow_up', 'transferred', 'dropped')", name=op.f('ck_calls_outcome_enum')),
    sa.CheckConstraint("sentiment IS NULL OR sentiment IN ('positive', 'neutral', 'negative')", name=op.f('ck_calls_sentiment_enum')),
    sa.CheckConstraint("status IN ('queued', 'ringing', 'in_progress', 'completed', 'failed', 'no_answer', 'busy', 'voicemail')", name=op.f('ck_calls_status_enum')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_calls_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_calls_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_calls_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls')),
    sa.UniqueConstraint('engine_call_id', name=op.f('uq_calls_engine_call_id'))
    )
    op.create_index(op.f('ix_calls_agent_id'), 'calls', ['agent_id'], unique=False)
    op.create_index(op.f('ix_calls_tenant_id'), 'calls', ['tenant_id'], unique=False)
    op.create_table('lead_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('status_change', 'note', 'call', 'notification')", name=op.f('ck_lead_events_type_enum')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_events_lead_id_leads'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_lead_events_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_events'))
    )
    op.create_index(op.f('ix_lead_events_lead_id'), 'lead_events', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_events_tenant_id'), 'lead_events', ['tenant_id'], unique=False)
    op.create_table('call_extractions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_extractions_call_id_calls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_call_extractions_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_extractions'))
    )
    op.create_index(op.f('ix_call_extractions_call_id'), 'call_extractions', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_extractions_tenant_id'), 'call_extractions', ['tenant_id'], unique=False)
    op.create_table('consent_ledger',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('phone_e164', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("purpose IN ('recording', 'callback', 'marketing')", name=op.f('ck_consent_ledger_purpose_enum')),
    sa.CheckConstraint("status IN ('granted', 'declined', 'withdrawn')", name=op.f('ck_consent_ledger_status_enum')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_consent_ledger_call_id_calls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_consent_ledger_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_ledger'))
    )
    op.create_index(op.f('ix_consent_ledger_tenant_id'), 'consent_ledger', ['tenant_id'], unique=False)
    op.create_table('transcript_turns',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_redacted', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("speaker IN ('agent', 'caller')", name=op.f('ck_transcript_turns_speaker_enum')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_transcript_turns_call_id_calls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_transcript_turns_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_turns')),
    sa.UniqueConstraint('call_id', 'idx', name=op.f('uq_transcript_turns_call_id_idx'))
    )
    op.create_index(op.f('ix_transcript_turns_call_id'), 'transcript_turns', ['call_id'], unique=False)
    op.create_index(op.f('ix_transcript_turns_tenant_id'), 'transcript_turns', ['tenant_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=True),
    sa.Column('unit_type', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost_paid', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("unit_type IN ('telephony_s', 'stt_s', 'tts_chars', 'llm_tok_in', 'llm_tok_out', 'platform_min', 'number_rental', 'other')", name=op.f('ck_usage_events_unit_type_enum')),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_usage_events_call_id_calls'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], name=op.f('fk_usage_events_tenant_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index(op.f('ix_usage_events_tenant_id'), 'usage_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # HAND-WRITTEN GOVERNANCE (hard rules 1, 4; DATA-MODEL §1, §10).
    # Autogenerate can never produce this block — do not remove it when
    # regenerating; RLS policies live IN migrations, never ad-hoc.
    # ------------------------------------------------------------------

    # 1. FORCEd RLS on every tenant table. FORCE makes even the table owner
    #    subject to the policy. Missing/invalid GUC ⇒ NULL ⇒ zero rows.
    tenant_tables = [
        "memberships", "invitations", "agents", "prompt_versions",
        "extraction_schemas", "phone_numbers", "calls", "transcript_turns",
        "call_extractions", "leads", "lead_events", "usage_events", "plans",
        "spend_state", "consent_ledger", "retention_policies",
        "deletion_requests", "inbound_webhooks", "outbound_webhooks",
    ]
    for table in tenant_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        # NULLIF: a pooled connection that once had the GUC returns '' (not NULL)
        # when it's unset — ''::uuid would ERROR instead of failing closed.
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
        )

    # organizations is the tenant root: the policy matches on id itself.
    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organizations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON organizations "
        "USING (id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
    )

    # 2. Append-only ledgers (hard rule 4): trigger-enforced because the app
    #    connects as the table owner (grants alone wouldn't bind it).
    #    Fixes are compensating entries, never UPDATE/DELETE.
    op.execute(
        """
        CREATE FUNCTION calevate_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only (hard rule 4): use a compensating entry',
                TG_TABLE_NAME USING ERRCODE = 'raise_exception';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    for table in ("usage_events", "consent_ledger", "audit_log"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION calevate_forbid_mutation()"
        )

    # 3. Slug immutability (DATA-MODEL §2: slugs are in client URLs, never change).
    op.execute(
        """
        CREATE FUNCTION calevate_forbid_slug_change() RETURNS trigger AS $$
        BEGIN
            IF NEW.slug IS DISTINCT FROM OLD.slug THEN
                RAISE EXCEPTION 'organizations.slug is immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER organizations_slug_immutable "
        "BEFORE UPDATE ON organizations "
        "FOR EACH ROW EXECUTE FUNCTION calevate_forbid_slug_change()"
    )

    # 4. Application role. The compose bootstrap user is a SUPERUSER and
    #    superusers bypass RLS entirely (FORCE included) — so the app NEVER
    #    connects as it. calevate_app: NOSUPERUSER NOBYPASSRLS, plain DML only.
    #    Migrations keep running as the owner (ALEMBIC_DATABASE_URL);
    #    the app's DATABASE_URL uses calevate_app. Password is a local-dev
    #    default — staging/prod set it from the secrets manager.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'calevate_app') THEN
                CREATE ROLE calevate_app LOGIN PASSWORD 'calevate_app'
                    NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
            END IF;
        END
        $$
        """
    )
    op.execute("GRANT USAGE ON SCHEMA public TO calevate_app")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO calevate_app"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO calevate_app"
    )
    # The append-only triggers still fire for calevate_app (they fire for everyone);
    # UPDATE/DELETE grants exist so non-ledger tables work normally.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_tenant_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_transcript_turns_tenant_id'), table_name='transcript_turns')
    op.drop_index(op.f('ix_transcript_turns_call_id'), table_name='transcript_turns')
    op.drop_table('transcript_turns')
    op.drop_index(op.f('ix_consent_ledger_tenant_id'), table_name='consent_ledger')
    op.drop_table('consent_ledger')
    op.drop_index(op.f('ix_call_extractions_tenant_id'), table_name='call_extractions')
    op.drop_index(op.f('ix_call_extractions_call_id'), table_name='call_extractions')
    op.drop_table('call_extractions')
    op.drop_index(op.f('ix_lead_events_tenant_id'), table_name='lead_events')
    op.drop_index(op.f('ix_lead_events_lead_id'), table_name='lead_events')
    op.drop_table('lead_events')
    op.drop_index(op.f('ix_calls_tenant_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_agent_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_prompt_versions_tenant_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_agent_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_phone_numbers_tenant_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_agent_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_inbound_webhooks_tenant_id'), table_name='inbound_webhooks')
    op.drop_table('inbound_webhooks')
    op.drop_index(op.f('ix_extraction_schemas_tenant_id'), table_name='extraction_schemas')
    op.drop_index(op.f('ix_extraction_schemas_agent_id'), table_name='extraction_schemas')
    op.drop_table('extraction_schemas')
    op.drop_table('spend_state')
    op.drop_index(op.f('ix_retention_policies_tenant_id'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_outbound_webhooks_tenant_id'), table_name='outbound_webhooks')
    op.drop_table('outbound_webhooks')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_tenant_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_deletion_requests_tenant_id'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('webhook_inbox_events')
    op.drop_table('webhook_deliveries')
    op.drop_table('users')
    op.drop_table('reserved_slugs')
    op.drop_index('ix_outbox_pending', table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_table('organizations')
    op.drop_index('ix_idempotency_expiry', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('admin_users')
    # ### end Alembic commands ###

    # Policies and triggers were dropped with their tables; the functions remain.
    op.execute("DROP FUNCTION IF EXISTS calevate_forbid_mutation()")
    op.execute("DROP FUNCTION IF EXISTS calevate_forbid_slug_change()")
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'calevate_app') THEN
                -- DROP OWNED revokes every privilege granted TO the role
                -- (including on alembic_version), which plain REVOKEs miss.
                DROP OWNED BY calevate_app;
                DROP ROLE calevate_app;
            END IF;
        END
        $$
        """
    )
