"""copilot memory — the episodic rows, their semantic distillate, and the clocks that end them

Revision ID: d4a9c17e6b02
Revises: e7c2f9a41d38
Create Date: 2026-08-31 00:00:00.000000

`apps/api/copilot/__init__.py` opened with "NOTHING IN THIS PACKAGE PERSISTS ANYTHING",
and cited `crm/assist.py:10-31`: a store of model-written prose about a person's screen
re-opens DPDP erasure and retention on a new surface. **This migration creates exactly
that store, so it also creates both of the things that sentence was protecting** — the
erasure arm and the retention clock — in the same revision as the table. That is the whole
shape of this file, and it is why it is longer than the DDL it carries.

WHAT THE TABLE HOLDS, AND THE TWO KINDS

* `kind = 'episodic'` — what happened: a question a person asked their console's copilot
  and the answer it gave, redacted on the way in (`copilot/memory.py::redacted_content`)
  and capped. Written by the copilot route in the transaction that already meters and
  audits the answer.
* `kind = 'semantic'` — a durable fact about the business, distilled OUT of a run of
  episodic rows by a background worker ("the clinic shuts Sunday"). Never written by a
  request.

NO EMBEDDING COLUMN, AND THAT IS A FINDING RATHER THAN AN OMISSION. The obvious design is
`vector(N)` + pgvector, and this repository cannot honestly ship it: **there is no
embedding path here to reuse.** D-28 made retrieval a managed API service that owns its
own embeddings, `apps/api/kb/models.KbDocument` says in terms "No embedding column, by
decision (D-28)", `kb_chunks` + pgvector are recorded as CONTINGENCY in
`apps/api/kb/__init__.py:11`, and `packages/shared/src/calevate_shared/config.py:766-774`
records `COHERE_API_KEY` being REMOVED because "NOTHING in this repository ever read it"
and "a knob that does nothing is worse than no knob". Grepped, not recalled: no
`CREATE EXTENSION vector`, no `vector(` in any migration, no embedding call anywhere in
`apps/`. So an embedding column here would be either (a) a column nobody populates —
CLAUDE.md's "a column nobody reads is a defect that looks like progress" — or (b) a new
vendor leg, a new credential and a reversal of D-28, none of which a memory feature is
entitled to decide.

What ships instead is a `search` tsvector — Postgres' own lexical index, which is real,
populated by the database itself, and needs no vendor. `copilot/memory.py::recall` blends
it with recency. The seam is written so a similarity channel can be added as a THIRD
retriever without changing a caller; see that module.

`'simple'`, NOT `'english'`, and the reason is the product. This platform is Telugu-first.
Postgres ships no Telugu configuration, and `english` applies English stemming and an
English stopword list — which does nothing useful for Telugu text and actively drops
tokens from it. `simple` lower-cases and splits and does nothing else, which is the same
(modest) behaviour in every script this console is used in. Cast to `::regconfig` because
a generated column requires an IMMUTABLE expression and only the explicit two-argument
form is immutable.

THE RETENTION CLOCK IS A NEW `data_category`, NOT A NEW MECHANISM. `retention_policies`
already IS the concept — a per-tenant TTL a client agreed to, swept nightly — and `kb` and
`engine_payload` were both added to it the same way (D-179). So this revision widens
`ck_retention_policies_category_enum`, seeds `copilot_memory` at 180 days / `delete` for
every organisation that already exists, and `apps/workers/retention.py` gains a probe arm
and a sweep arm. 180 days: shorter than the transcript clock because nothing depends on
these rows — they are working context, regenerated by use, and the client bought none of
it — and `delete` because there is no anonymised form of a sentence (the `kb` arm's
argument, verbatim).

`action` IS NOT READ by the sweep arm, exactly as on `kb` and `engine_payload`, and this
is stated here rather than left as a silent omission: a policy row saying `anonymize`
deletes, because a blanked memory row is a row the recall query still pays for and the
model still reads, carrying nothing.

AND THE SWEEP HAS TO BE ABLE TO REACH THE TENANT. `retention._due_tenants` derives its
worklist from `engine_agent_routes` UNION `retention_worklist`, and a tenant can hold
copilot memories with no published agent — an owner mid-onboarding asking the copilot
about the screen they are filling in is the ordinary case, not the corner. That is the
same hole D-368 found for `kb_sources`, so it gets D-368's answer rather than a second
one: a `retention_worklist` reason and an AFTER INSERT trigger that registers it.
`register_retention_worklist()` is REPLACED with a version that takes the reason as
`TG_ARGV[0]` and the `kb_sources` trigger is recreated passing `'kb_source'`, so there is
ONE registration function rather than one per writer (CLAUDE.md: one way per problem). The
downgrade restores the single-purpose original exactly.

The worklist is also what lets the DISTILLATION cron find work: it runs under
`untenanted_session`, `copilot_memories` is FORCE-RLS'd and would return zero rows to it,
and `retention_worklist_ops_read` already grants an untenanted session the tenant IDS and
nothing else. No second bridge, and no RLS exemption on a table holding client prose —
which is the cost `_due_tenants` explicitly refused to pay for `kb_sources`.

REVERSIBILITY. `downgrade()` drops the table, the trigger, the policy, the seeded
retention rows and the widened CHECK, and restores the original one-reason function. The
`copilot_memory` worklist rows are deleted BEFORE the CHECK narrows, or the narrowed
constraint would be created against rows that violate it. Nothing here is a record of
something that happened (hard rule 4's concern): every row is derived from a conversation
that was already metered in `usage_events` and audited in `audit_log`, both of which
survive.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d4a9c17e6b02"
down_revision: str | None = "e7c2f9a41d38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "copilot_memories"

# DATA-MODEL §1 verbatim, with `d5b8a2c60e17`'s NULLIF: a pooled connection that once had
# the GUC returns '' when unset, and ''::uuid ERRORs instead of failing closed.
_POLICY = (
    f"CREATE POLICY tenant_isolation ON {TABLE} USING ("
    "tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)"
)

# Literals, never imports. A migration is a snapshot of the schema on the day it ran
# (the rule `c2f7a91b4e63` states and `b2e6f10c94d7` repeats), so a constant edited later
# must not change what this file did.
_CATEGORY = "copilot_memory"
_WORKLIST_REASON = "copilot_memory"
_CATEGORIES_BEFORE = ("recording", "transcript", "lead", "consent_log", "engine_payload", "kb")
_CATEGORIES_AFTER = (*_CATEGORIES_BEFORE, _CATEGORY)
_REASONS_BEFORE = ("kb_source",)
_REASONS_AFTER = (*_REASONS_BEFORE, _WORKLIST_REASON)


def _in_list(values: Sequence[str]) -> str:
    """`('a', 'b')` as SQL — NOT `repr(tuple)`, which the rest of this repo uses and which
    emits `('kb_source',)` for a one-element tuple. That trailing comma is a syntax error
    in an `IN` list, and `retention_worklist` has exactly one reason today, so the
    downgrade would have failed on the one path nobody runs until they need it."""
    return "(" + ", ".join(f"'{value}'" for value in values) + ")"

#: The default this migration seeds for organisations that already exist. See the module
#: docstring; `scripts/seed.DEFAULT_RETENTION_POLICIES` carries the same pair for the ones
#: created after it, and `tests/copilot_memory_retention_test.py` asserts they agree.
_TTL_DAYS = 180
_ACTION = "delete"

_WORKLIST_FN = "register_retention_worklist"
_KB_TRIGGER = "kb_source_registers_retention_worklist"
_MEMORY_TRIGGER = "copilot_memory_registers_retention_worklist"

#: The reason-taking replacement. `TG_ARGV[0]` is the argument the CREATE TRIGGER supplies,
#: so one function serves every writer; `quote_literal`/format is not needed because the
#: value is bound as a parameter of the INSERT rather than concatenated into SQL.
_WORKLIST_FN_MULTI = f"""
CREATE OR REPLACE FUNCTION {_WORKLIST_FN}() RETURNS trigger AS $$
BEGIN
    INSERT INTO retention_worklist (tenant_id, reason)
    VALUES (NEW.tenant_id, TG_ARGV[0])
    ON CONFLICT (tenant_id, reason) DO NOTHING;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql
"""

#: `b2e6f10c94d7`'s original, restored on the way down so a downgraded database is the
#: database that migration left rather than one that merely behaves like it.
_WORKLIST_FN_SINGLE = f"""
CREATE OR REPLACE FUNCTION {_WORKLIST_FN}() RETURNS trigger AS $$
BEGIN
    INSERT INTO retention_worklist (tenant_id, reason)
    VALUES (NEW.tenant_id, 'kb_source')
    ON CONFLICT (tenant_id, reason) DO NOTHING;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql
"""


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '3s'")

    op.create_table(
        TABLE,
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        # WHOSE memory. RLS answers "which tenant" and never "which person"
        # (`lead_saved_views`' comment, and the same split here): every read in
        # `copilot/memory.py` carries an explicit `user_id =` predicate, because one
        # colleague's console conversation is not another's context.
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        # The route the episode happened on — a screen name, never a record id
        # (`copilot/routes.py` audits the same value for the same reason). NULL on a
        # semantic row: a fact about the business belongs to no one screen, and the CHECK
        # below makes that a schema property rather than a convention.
        sa.Column("screen_route", sa.String(length=200), nullable=True),
        # Counts, ids and flags. NEVER text a person or a model wrote — that is `content`,
        # which is the one column the redaction pass covers.
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        # Episodic only: when a distillation run CONSUMED this row. It is the job's whole
        # idempotency (`apps/workers/copilot_memory.py`) — stamped in the same transaction
        # as the semantic rows it produced, so a re-run finds nothing and a crash between
        # them rolls both back together.
        sa.Column("distilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('episodic', 'semantic')", name=op.f("ck_copilot_memories_kind_enum")
        ),
        # A memory with nothing in it is not a memory, and a blank row would still be
        # returned by recall, still cost prompt tokens and still say nothing.
        sa.CheckConstraint(
            "length(btrim(content)) > 0", name=op.f("ck_copilot_memories_content_not_blank")
        ),
        # THE SPEND BOUND, in the schema rather than in the writer. `recall` puts these
        # rows in a prompt on every copilot turn, so an unbounded `content` is unbounded
        # paid input tokens. 2000 is `copilot/schemas._MAX_TEXT` — the same ceiling the
        # wire already puts on one field value and one history turn — so no legitimate
        # episode can exceed it and the distiller cannot write an essay.
        sa.CheckConstraint("length(content) <= 2000", name=op.f("ck_copilot_memories_content_cap")),
        sa.CheckConstraint(
            "kind <> 'semantic' OR screen_route IS NULL",
            name=op.f("ck_copilot_memories_semantic_has_no_screen"),
        ),
        sa.CheckConstraint(
            "kind = 'episodic' OR distilled_at IS NULL",
            name=op.f("ck_copilot_memories_only_episodic_is_distilled"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_copilot_memories")),
    )

    # THE RECENCY CHANNEL, and the user scoping every read carries. Leading
    # `(tenant_id, user_id)` because no query filters one without the other; `created_at
    # DESC` because "this person's last few exchanges" is the read, and it is also what
    # the nightly sweep and the distiller walk (both inside a tenant session, so the
    # tenant_id prefix is the whole of their selectivity — deliberately NOT a second
    # `(tenant_id, created_at)` index, per D-192: an index nobody measured is a write cost
    # this table has not earned).
    op.create_index(
        op.f("ix_copilot_memories_tenant_user_recent"),
        TABLE,
        ["tenant_id", "user_id", sa.text("created_at DESC")],
        unique=False,
    )
    # THE RELEVANCE CHANNEL. A GIN index over the generated tsvector — the one thing here
    # that stands in for a similarity search, and the reason it is honest to call the
    # recall hybrid rather than semantic.
    op.execute(
        f"ALTER TABLE {TABLE} ADD COLUMN search tsvector "
        "GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, content)) STORED"
    )
    op.execute(f"CREATE INDEX ix_copilot_memories_search ON {TABLE} USING gin (search)")
    # THE DISTILLER'S WORK LIST. Partial, so it holds only what is outstanding: once a run
    # stamps `distilled_at` the row leaves the index, which keeps the cron's scan
    # proportional to the backlog rather than to the history.
    op.create_index(
        op.f("ix_copilot_memories_pending_distillation"),
        TABLE,
        ["tenant_id", "user_id", "screen_route", "created_at"],
        unique=False,
        postgresql_where=sa.text("kind = 'episodic' AND distilled_at IS NULL"),
    )

    # NOT VALID then VALIDATE — `d5b8a2c60e17`'s locking shape.
    #
    # `organizations` RESTRICT: offboarding is an explicit workflow, never a cascade
    # (`db/base.TenantMixin`). `users` CASCADE: `lead_saved_views` already made that
    # choice for per-user console state, and it is the right one here — a deleted user's
    # console memories have no subject left, and RESTRICT would make the row block the
    # deletion of the person it is about.
    for statement in (
        f"ALTER TABLE {TABLE} ADD CONSTRAINT fk_copilot_memories_tenant_id_organizations "
        "FOREIGN KEY (tenant_id) REFERENCES organizations (id) ON DELETE RESTRICT NOT VALID",
        f"ALTER TABLE {TABLE} ADD CONSTRAINT fk_copilot_memories_user_id_users "
        "FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT VALID",
    ):
        op.execute(statement)
    op.execute("SET LOCAL lock_timeout = '3s'")
    for constraint in (
        "fk_copilot_memories_tenant_id_organizations",
        "fk_copilot_memories_user_id_users",
    ):
        op.execute(f"ALTER TABLE {TABLE} VALIDATE CONSTRAINT {constraint}")

    # Hard rule 1, in the same migration as the table it protects.
    op.execute(f"ALTER TABLE {TABLE} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {TABLE} FORCE ROW LEVEL SECURITY")
    op.execute(_POLICY)

    # --- the retention clock ----------------------------------------------------------
    op.execute("ALTER TABLE retention_policies DROP CONSTRAINT ck_retention_policies_category_enum")
    op.execute(
        "ALTER TABLE retention_policies ADD CONSTRAINT ck_retention_policies_category_enum "
        f"CHECK (data_category IN {_in_list(_CATEGORIES_AFTER)})"
    )
    # The reach backwards. Runs as the owner role — the only session that sees every
    # tenant — for `b2e6f10c94d7`'s reason: without it, every organisation created before
    # today holds copilot memories no policy row expires, which is the hole this whole
    # section exists to close rather than one it is allowed to open.
    op.execute(
        "INSERT INTO retention_policies (id, tenant_id, data_category, ttl_days, action, "
        f"created_at) SELECT gen_random_uuid(), id, '{_CATEGORY}', {_TTL_DAYS}, '{_ACTION}', "
        "now() FROM organizations "
        "ON CONFLICT ON CONSTRAINT uq_retention_policies_tenant_id_data_category DO NOTHING"
    )

    # --- the worklist bridge ----------------------------------------------------------
    op.execute(
        "ALTER TABLE retention_worklist DROP CONSTRAINT ck_retention_worklist_reason_enum"
    )
    op.execute(
        "ALTER TABLE retention_worklist ADD CONSTRAINT ck_retention_worklist_reason_enum "
        f"CHECK (reason IN {_in_list(_REASONS_AFTER)})"
    )
    op.execute(_WORKLIST_FN_MULTI)
    # Recreated so it passes its reason explicitly. Dropped and created rather than
    # `CREATE OR REPLACE TRIGGER` (PG14+) because the DROP makes the downgrade symmetric.
    op.execute(f"DROP TRIGGER IF EXISTS {_KB_TRIGGER} ON kb_sources")
    op.execute(
        f"CREATE TRIGGER {_KB_TRIGGER} AFTER INSERT ON kb_sources "
        f"FOR EACH ROW EXECUTE FUNCTION {_WORKLIST_FN}('kb_source')"
    )
    op.execute(
        f"CREATE TRIGGER {_MEMORY_TRIGGER} AFTER INSERT ON {TABLE} "
        f"FOR EACH ROW EXECUTE FUNCTION {_WORKLIST_FN}('{_WORKLIST_REASON}')"
    )


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '3s'")

    op.execute(f"DROP TRIGGER IF EXISTS {_MEMORY_TRIGGER} ON {TABLE}")
    op.execute(f"DROP TRIGGER IF EXISTS {_KB_TRIGGER} ON kb_sources")
    op.execute(_WORKLIST_FN_SINGLE)
    op.execute(
        f"CREATE TRIGGER {_KB_TRIGGER} AFTER INSERT ON kb_sources "
        f"FOR EACH ROW EXECUTE FUNCTION {_WORKLIST_FN}()"
    )
    # BEFORE the CHECK narrows: a constraint added over rows that violate it fails, and
    # the failure would be reported against the ALTER rather than against the rows.
    op.execute(f"DELETE FROM retention_worklist WHERE reason = '{_WORKLIST_REASON}'")
    op.execute(
        "ALTER TABLE retention_worklist DROP CONSTRAINT ck_retention_worklist_reason_enum"
    )
    op.execute(
        "ALTER TABLE retention_worklist ADD CONSTRAINT ck_retention_worklist_reason_enum "
        f"CHECK (reason IN {_in_list(_REASONS_BEFORE)})"
    )

    op.execute(f"DELETE FROM retention_policies WHERE data_category = '{_CATEGORY}'")
    op.execute("ALTER TABLE retention_policies DROP CONSTRAINT ck_retention_policies_category_enum")
    op.execute(
        "ALTER TABLE retention_policies ADD CONSTRAINT ck_retention_policies_category_enum "
        f"CHECK (data_category IN {_in_list(_CATEGORIES_BEFORE)})"
    )

    op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {TABLE}")
    op.execute("DROP INDEX IF EXISTS ix_copilot_memories_search")
    op.drop_index(op.f("ix_copilot_memories_pending_distillation"), table_name=TABLE)
    op.drop_index(op.f("ix_copilot_memories_tenant_user_recent"), table_name=TABLE)
    op.drop_table(TABLE)
