"""Opaque server-side sessions: issue, verify, rotate, revoke (D-165).

═══ WHAT A SESSION IS HERE ═══

A 256-bit random string the browser holds in an `HttpOnly` cookie, and a row that IS the
session. The string carries no claims, so there is nothing in it to trust and nothing to
verify cryptographically; every question about it — is it live, whose is it, which realm,
did it pass MFA, when does it die — is answered by the row. That is the property this
product cannot trade away: **revocation takes effect on the next request**, with no
denylist, no token lifetime to tune down, and no window during which a removed staff
member, a deactivated operator or a halted tenant still has a valid credential in hand.

Rejected: a stateless JWT session. It is the fashionable answer and it is the wrong one
for a dashboard whose authorization is re-read per request anyway (`core/auth.py`
re-checks `is_active` and `admin_users` on every call, BACKEND-PATTERNS §7), because the
only way to revoke one is a server-side denylist — which is a session table with worse
ergonomics and a failure mode where the denylist being down means revocation silently
stops working. OWASP's ASVS 5.0 moved self-contained tokens into their own chapter (V9)
precisely because their operational requirements — key rotation, revocation — are the
part people skip. We already run one signed-token design (`core/impersonation.py`'s
15-minute view-as grant) and it is signed exactly because it is NOT a credential and
needs no revocation of its own.

═══ THE REALM BOUNDARY, WHICH IS THE DANGEROUS PART ═══

Today the two realms are two Clerk applications with two JWKS endpoints, so an admin
token is not a weak client token — it is not a token at all (`core/auth.py::jwks_url`).
When both realms are ours, that separation has to be rebuilt out of our own materials,
and "a `realm` column we remember to filter on" is not good enough: it is one forgotten
WHERE clause away from being nothing, and the forgotten clause would be silent.

So the realm is INSIDE THE HASH. `token_fingerprint` domain-separates on it, which means
the stored fingerprint of a client token computed under the admin realm is a different
32 bytes — there is no value the admin lookup could compare it against and match. Passing
a client's token to `verify_session(..., realm="admin")` therefore returns "no such
session" as a matter of arithmetic, before any column is read. The `AND realm = :realm`
predicate in the query stays anyway, as the belt to that brace: two independent reasons
for the same refusal, and `tests/authn_session_test.py` drives both.

═══ ROTATION AND REUSE DETECTION ═══

OWASP's Session Management Cheat Sheet requires the session identifier to be "renewed or
regenerated by the web application after any privilege level change", which is the
session-fixation defence. `rotate_session` is that: it mints a new token, marks the old
row `superseded_at` under a compare-and-swap, and inserts a new row carrying the same
`family_id` and the same `absolute_expires_at` — rotation refreshes the CREDENTIAL, never
the lifetime, or a session that rotates often would live forever.

Because the old row survives with `superseded_at` set, presenting the old token later is
DETECTABLE, and it is treated as theft rather than as a stale tab: the whole family is
revoked with `reuse_detected`. That is RFC 9700 §4.14.2's refresh-token reuse rule, and
the reference implementation this migration learns from arrived at the same answer the
expensive way — its pentest finding F-2 (2026-08-15) was exactly a replayed rotated
token being read as a stale request.

**WITHOUT ITS CONCURRENCY GRACE WINDOW**, which is the one design decision here that
departs from that reference, so it is argued rather than assumed. Their rotation happens
on every access-token refresh, so parallel tabs racing the same refresh token is the
ORDINARY case and a 10-second grace was the only way to stop legitimate users being
logged out. Ours rotates on PRIVILEGE CHANGE ONLY — sign-in, MFA completion, role change
— which are single user-initiated actions, never a burst of background fetches. A grace
window here would buy nothing and would sell a 10-second replay window for it.

═══ TIMEOUTS ═══

Both bounds are enforced server-side, on the row, per OWASP: an idle bound so an
unattended browser stops being a credential, and an absolute bound so a stolen cookie
stops being one even while the victim keeps working. The two realms get different numbers
because their blast radii differ by an order of magnitude — see `REALM_TIMEOUTS`.

═══ WHO OWNS THE TRANSACTION ═══

Everything here takes an `AsyncSession` — a sign-in is a credential check, a session
insert and an audit row, and those belong in one transaction — with ONE exception.
`verify_session` opens its own, because the family revocation it performs on a replayed
token has to survive the refusal that same branch produces; its docstring argues it, and
`tests/authn_session_test.py::test_replaying_a_rotated_token_revokes_the_whole_family`
is the test that goes red if it is ever taken back.
"""

from __future__ import annotations

import hashlib
import secrets
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Final
from uuid import UUID

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.authn.models import AUTHN_REALMS
from apps.api.core.errors import ProblemError
from apps.api.core.logging import get_logger
from apps.api.db.base import uuid7
from apps.api.db.result import rowcount_of
from apps.api.db.session import credential_session

log = get_logger(__name__)

#: 32 bytes of `secrets.token_urlsafe` entropy — 256 bits, against the 64-bit floor
#: OWASP's Session Management Cheat Sheet sets. The margin is free (43 characters in a
#: cookie) and it is what lets the fingerprint below be a fast hash.
TOKEN_ENTROPY_BYTES: Final = 32

#: The hash domain. Versioned so that changing the token format later is a new domain
#: rather than a reinterpretation of the old one, and realm-separated for the reason the
#: module docstring gives.
_FINGERPRINT_DOMAIN: Final = b"calevate/auth-session/v1/"


@dataclass(frozen=True, slots=True)
class RealmTimeouts:
    """How long a session of one realm may sit idle, and how long it may live at all."""

    idle: timedelta
    absolute: timedelta


#: WHY THE TWO REALMS DIFFER, since a single pair of numbers would have been simpler.
#:
#: The admin realm holds the big red switch, the tenant directory and D-22 view-as; one
#: compromised operator session reaches every client's data. OWASP suggests 2-5 minutes of
#: idle for "high-value applications" and 15-30 for low-risk ones, with 4-8 hours absolute
#: for an office-worker scenario. Two to five minutes would be a control that gets
#: switched off — an operator lifting a halt at 3am must not be re-authenticating between
#: clicks — so the admin realm takes the strict end of the low-risk band (30 minutes idle)
#: and the absolute bound OWASP names for a working day (8 hours). A shift ends; so does
#: the session.
#:
#: The client realm is one business's own data, read by that business's owner on a phone
#: with the tab open all day. Thirty minutes there is a product that logs you out while
#: you look at a lead, and the mitigation people reach for is "remember me forever". So:
#: twelve hours idle, and fourteen days absolute — the absolute bound is what makes a
#: stolen cookie expire on its own, and it is meaningful precisely because revocation
#: (`revoke_subject_sessions`) can end every one of them the instant we learn something.
#:
#: These are constants, not console config: a per-tenant idle timeout is a knob whose only
#: use is turning the control off, and `core/platform_config.py`'s doctrine is that a
#: security posture invertible from a web form at 3am is not a posture.
REALM_TIMEOUTS: Final[dict[str, RealmTimeouts]] = {
    "admin": RealmTimeouts(idle=timedelta(minutes=30), absolute=timedelta(hours=8)),
    "client": RealmTimeouts(idle=timedelta(hours=12), absolute=timedelta(days=14)),
}

#: How stale `last_seen_at` may get before a verification pays for a write.
#:
#: Sliding the idle window on every request would mean one UPDATE per API call, and this
#: console opens ~6 polling subscriptions per screen — the same volume argument
#: `core/auth.py::_record_impersonated_read` makes about audit rows, one layer down. A
#: minute of granularity costs at most a minute of idle timeout and turns a write per
#: request into a write per minute per session.
IDLE_WRITE_FLOOR: Final = timedelta(seconds=60)


@dataclass(frozen=True, slots=True)
class IssuedSession:
    """A new session: the row's identity, and the ONE moment its token exists in clear.

    The token is returned and never stored — only `token_fingerprint(...)` of it reaches
    the database — so this object is the single point at which the caller can put it in a
    `Set-Cookie` header. It must not be logged (hard rule 6 is about PII; this is worse
    than PII, it is the credential itself).
    """

    session_id: UUID
    family_id: UUID
    token: str
    absolute_expires_at: datetime


@dataclass(frozen=True, slots=True)
class VerifiedSession:
    """A live session, as the row describes it. Ids and instants only.

    `mfa_verified_at` is carried rather than recomputed for the reason
    `core/auth.py::VerifiedToken.second_factor_age_min` is: it is a property of the
    CREDENTIAL, and nothing downstream may re-decide it.
    """

    session_id: UUID
    family_id: UUID
    realm: str
    subject_id: UUID
    absolute_expires_at: datetime
    mfa_verified_at: datetime | None


#: Why `verify_session` said no. STABLE CODES FOR US, never for the wire — every one of
#: them produces the same sentence to the caller (`_session_expired`), because "that token
#: was real but expired" tells a holder of a stolen cookie something. They exist so the
#: operator's log line and this suite's assertions can name the branch without inventing
#: an oracle.
REFUSALS: Final = ("unknown", "reuse_detected", "revoked", "idle_expired", "absolute_expired")


@dataclass(frozen=True, slots=True)
class SessionOutcome:
    """What a verification concluded — a live session, or a named refusal.

    ═══ WHY THIS IS A RETURN VALUE AND NOT AN EXCEPTION ═══

    Because ONE refusal has a side effect that must survive it. Detecting a replayed token
    revokes the whole family (`reuse_detected`) — that UPDATE is the entire point of the
    branch, and it is the branch that also has to say no. A `verify_session` that raised
    from inside its own transaction would roll its own revocation back: the thief's replay
    would be refused, the victim's live session would stay live, and the control would be
    a log line.

    So the transaction is closed BEFORE anything is refused, and `verify_session` owns it
    rather than taking one (see that function). This type is what carries the verdict out
    across that boundary. `require_live()` then raises the one refusal every failure
    produces, from a point where there is no transaction left to lose.

    `refusal` is a stable code FOR US — a log line, a metric, an assertion — and never for
    the wire, because "that token was real but expired" tells the holder of a stolen
    cookie something.
    """

    session: VerifiedSession | None
    refusal: str | None

    @property
    def live(self) -> bool:
        return self.session is not None

    def require_live(self) -> VerifiedSession:
        """The session, or the ONE refusal every failure produces.

        Safe to call anywhere: `verify_session` has already committed by the time this
        object exists.
        """
        if self.session is None:
            raise _session_expired()
        return self.session


def _refuse_unknown_realm(realm: str) -> None:
    if realm not in AUTHN_REALMS:
        # A programming error, not a caller error: `realm` is never taken from the wire,
        # it is chosen by whichever dependency is asking. Refusing loudly beats writing a
        # row into a realm the CHECK constraint would reject three statements later.
        raise ValueError(f"{realm!r} is not an authentication realm ({', '.join(AUTHN_REALMS)})")


def new_token() -> str:
    """A fresh bearer token. URL-safe so it survives a cookie value unencoded."""
    return secrets.token_urlsafe(TOKEN_ENTROPY_BYTES)


def token_fingerprint(token: str, realm: str) -> bytes:
    """What we store instead of the token: SHA-256 over a realm-separated domain.

    A FAST HASH IS THE CORRECT CHOICE HERE, and this is the point at which the reference
    implementation went wrong (it bcrypts its refresh tokens, then compares a presented
    token against stored hashes in a loop — one deliberately-slow KDF per candidate row).
    A slow KDF exists to make GUESSING the preimage expensive. The preimage here is 256
    bits from `secrets.token_urlsafe`, so guessing is not on the table at any speed, and
    all a slow hash buys is a lookup that cannot use an index — the stored value has to be
    comparable for equality to find the row at all.

    What the hash IS for: a database dump must not be a drawer of live cookies. SHA-256 of
    a 256-bit random value is irreversible in the only sense that matters here.

    THE REALM IS INSIDE THE DIGEST, not merely beside it in a column. See the module
    docstring: it makes cross-realm confusion arithmetic rather than a WHERE clause
    somebody has to remember.
    """
    _refuse_unknown_realm(realm)
    return hashlib.sha256(_FINGERPRINT_DOMAIN + realm.encode() + b"\x00" + token.encode()).digest()


async def issue_session(
    session: AsyncSession,
    *,
    realm: str,
    subject_id: UUID,
    mfa_verified_at: datetime | None = None,
    now: datetime | None = None,
) -> IssuedSession:
    """Start a NEW session family for a subject who has just proved who they are.

    Callers must have verified a credential first — this function checks nothing about
    the subject, by design: it is the session layer, and mixing "is this the right
    password" into it would be the same conflation that lets a reset flow accidentally
    become a login flow.

    Requires a `credential_session()`. Every other session in this process sees no rows
    in `auth_sessions`, so an INSERT from one would be refused by the FORCEd policy's
    WITH CHECK rather than silently landing somewhere unreadable.
    """
    _refuse_unknown_realm(realm)
    issued_at = now or datetime.now(UTC)
    timeouts = REALM_TIMEOUTS[realm]
    token = new_token()
    session_id, family_id = uuid7(), uuid7()
    absolute_expires_at = issued_at + timeouts.absolute
    await session.execute(
        text(
            "INSERT INTO auth_sessions (id, family_id, realm, subject_id, token_hash, "
            "last_seen_at, idle_expires_at, absolute_expires_at, mfa_verified_at, "
            "created_at, updated_at) "
            "VALUES (:id, :fam, :realm, :sub, :hash, :now, :idle, :abs, :mfa, :now, :now)"
        ),
        {
            "id": session_id,
            "fam": family_id,
            "realm": realm,
            "sub": subject_id,
            "hash": token_fingerprint(token, realm),
            "now": issued_at,
            "idle": issued_at + timeouts.idle,
            "abs": absolute_expires_at,
            "mfa": mfa_verified_at,
        },
    )
    # Ids only. The token is the one value in this frame that must never be logged.
    log.info("auth_session_issued", extra={"realm": realm, "session_id": str(session_id)})
    return IssuedSession(
        session_id=session_id,
        family_id=family_id,
        token=token,
        absolute_expires_at=absolute_expires_at,
    )


def _session_expired() -> ProblemError:
    """ONE refusal for every way a session can fail to be usable.

    Absent, unknown, tampered, expired, idled out, revoked, replayed and belonging to the
    other realm all produce this. Distinguishing them would be an oracle — "that token was
    real but expired" tells a holder of a stolen cookie something — and the caller has the
    same next step in every case. The DISTINCTION is logged, where the operator is.
    """
    return ProblemError.unauthorized("Your session is not valid. Sign in again.")


async def verify_session(*, token: str, realm: str, now: datetime | None = None) -> SessionOutcome:
    """Turn a presented token into a live session for THIS realm, or a named refusal.

    ═══ THIS FUNCTION OWNS ITS TRANSACTION, AND THAT IS THE DESIGN ═══

    It is the ONE function in this package that does not take an `AsyncSession`, because
    it is the one whose write must outlive the request that triggered it. Detecting a
    replayed token revokes the whole family; run inside the caller's transaction, that
    revocation is undone by the refusal it causes — the thief's replay is refused, the
    victim's live session survives, and reuse detection becomes a log line. Every
    arrangement that kept the caller's transaction had the same hole one level up: the
    caller's `async with` unwinds on the `ProblemError` however politely the refusal is
    packaged, and only a caller who remembered to raise afterwards would be correct.

    A SECOND session opened for the revocation was the other fix and is refused:
    `db/session.py` states — and `max_overflow=0` relies on — that no code path holds two
    sessions at once, and the reuse branch is one an attacker can reach on demand by
    replaying a token, so it would be a pool-exhaustion lever rather than a rare cost.

    What that buys, beyond correctness: the idle-window slide also stops depending on
    whether the REQUEST succeeded. `resolve_mirrored_user` in `core/clerk_identity.py` is
    the precedent — an authentication-time read that owns its own session for the same
    reason.

    One statement finds the row (the fingerprint is unique and indexed); everything after
    it is a decision about that row, in the order that makes the reuse signal reachable:

      1. **No row** — never issued, tampered with, or minted for the other realm.
      2. **`superseded_at` set** — this token was rotated away and is being presented
         again. Two parties hold it, so it leaked: revoke the FAMILY. Checked before
         revocation and expiry deliberately, because a replay of an expired-but-superseded
         token is still evidence of a leak.
      3. **Revoked, or past either bound.**
      4. Otherwise: slide the idle window (throttled) and answer with the session.

    `now` is injectable so the expiry branches are testable without sleeping or moving a
    clock; every caller in the application passes nothing.
    """
    _refuse_unknown_realm(realm)
    async with credential_session() as session:
        return await _verify_within(session, token=token, realm=realm, now=now)


async def _verify_within(
    session: AsyncSession, *, token: str, realm: str, now: datetime | None
) -> SessionOutcome:
    """The decision itself, on a session that is COMMITTED by the caller above.

    Split out rather than inlined so that the transaction boundary is one line the reader
    can see, and so nothing in the decision can be tempted to raise: every exit below is a
    `return`, and the only way this function's writes are lost is a database error, which
    is the case where losing them is correct.
    """
    at = now or datetime.now(UTC)
    row = (
        await session.execute(
            text(
                "SELECT id, family_id, subject_id, absolute_expires_at, idle_expires_at, "
                "last_seen_at, superseded_at, revoked_at, mfa_verified_at "
                "FROM auth_sessions WHERE token_hash = :hash AND realm = :realm"
            ),
            {"hash": token_fingerprint(token, realm), "realm": realm},
        )
    ).first()
    if row is None:
        log.info("auth_session_unknown", extra={"realm": realm})
        return SessionOutcome(session=None, refusal="unknown")

    (
        session_id,
        family_id,
        subject_id,
        absolute_expires_at,
        idle_expires_at,
        last_seen_at,
        superseded_at,
        revoked_at,
        mfa_verified_at,
    ) = row

    if superseded_at is not None:
        log.warning(
            "auth_session_reuse_detected",
            extra={"realm": realm, "session_id": str(session_id), "family_id": str(family_id)},
        )
        await revoke_family(
            session, family_id=UUID(str(family_id)), reason="reuse_detected", now=at
        )
        return SessionOutcome(session=None, refusal="reuse_detected")
    if revoked_at is not None:
        log.info("auth_session_not_live", extra={"realm": realm, "session_id": str(session_id)})
        return SessionOutcome(session=None, refusal="revoked")
    if at >= absolute_expires_at:
        log.info("auth_session_not_live", extra={"realm": realm, "session_id": str(session_id)})
        return SessionOutcome(session=None, refusal="absolute_expired")
    if at >= idle_expires_at:
        log.info("auth_session_not_live", extra={"realm": realm, "session_id": str(session_id)})
        return SessionOutcome(session=None, refusal="idle_expired")

    if at - last_seen_at >= IDLE_WRITE_FLOOR:
        # Guarded on `revoked_at IS NULL AND superseded_at IS NULL` even though both were
        # just read: a concurrent sign-out between the SELECT and here must not have its
        # revocation quietly outlived by a slide. Losing this race is a skip, not a fault
        # (BACKEND-PATTERNS §5) — the read above already decided this request.
        await session.execute(
            text(
                "UPDATE auth_sessions SET last_seen_at = :now, idle_expires_at = :idle, "
                "updated_at = :now WHERE id = :id AND revoked_at IS NULL "
                "AND superseded_at IS NULL"
            ),
            {"now": at, "idle": at + REALM_TIMEOUTS[realm].idle, "id": session_id},
        )

    return SessionOutcome(
        session=VerifiedSession(
            session_id=UUID(str(session_id)),
            family_id=UUID(str(family_id)),
            realm=realm,
            subject_id=UUID(str(subject_id)),
            absolute_expires_at=absolute_expires_at,
            mfa_verified_at=mfa_verified_at,
        ),
        refusal=None,
    )


async def rotate_session(
    session: AsyncSession,
    *,
    verified: VerifiedSession,
    mfa_verified_at: datetime | None = None,
    now: datetime | None = None,
) -> IssuedSession:
    """Replace the credential of a live session, keeping the session.

    Called at every privilege change — sign-in over an anonymous session, second-factor
    completion, a role change — which is what OWASP's session-fixation defence asks for.

    `absolute_expires_at` is CARRIED FORWARD, never recomputed: a session that rotates
    must not be able to outlive the bound it was born with, or an attacker with a foothold
    could keep one alive indefinitely by rotating it.

    The supersede is a compare-and-swap on `superseded_at IS NULL`. Losing it means
    another rotation of the same row won, and the loser refuses rather than minting a
    second live token in one family — a family with two live members is precisely the
    state the reuse detector reads as theft.

    `mfa_verified_at` defaults to the value the old session carried, so an ordinary
    rotation cannot silently DOWNGRADE a session that had completed a second factor; pass
    it explicitly to record that a factor was just verified.

    THIS ONE RAISES, unlike `verify_session`, and the difference is not stylistic: the
    only failure here is a lost compare-and-swap, which by definition wrote nothing. There
    is no side effect for the rollback to eat, so the exception is free — and the caller's
    whole request should fail anyway, because it asked to rotate a session that is no
    longer the live one.
    """
    at = now or datetime.now(UTC)
    superseded = await session.execute(
        text(
            "UPDATE auth_sessions SET superseded_at = :now, updated_at = :now "
            "WHERE id = :id AND superseded_at IS NULL AND revoked_at IS NULL"
        ),
        {"now": at, "id": verified.session_id},
    )
    if rowcount_of(superseded) == 0:
        log.warning(
            "auth_session_rotation_lost",
            extra={"realm": verified.realm, "session_id": str(verified.session_id)},
        )
        raise _session_expired()

    token = new_token()
    session_id = uuid7()
    await session.execute(
        text(
            "INSERT INTO auth_sessions (id, family_id, realm, subject_id, token_hash, "
            "last_seen_at, idle_expires_at, absolute_expires_at, mfa_verified_at, "
            "created_at, updated_at) "
            "VALUES (:id, :fam, :realm, :sub, :hash, :now, :idle, :abs, :mfa, :now, :now)"
        ),
        {
            "id": session_id,
            "fam": verified.family_id,
            "realm": verified.realm,
            "sub": verified.subject_id,
            "hash": token_fingerprint(token, verified.realm),
            "now": at,
            "idle": at + REALM_TIMEOUTS[verified.realm].idle,
            "abs": verified.absolute_expires_at,
            "mfa": mfa_verified_at if mfa_verified_at is not None else verified.mfa_verified_at,
        },
    )
    log.info(
        "auth_session_rotated",
        extra={"realm": verified.realm, "session_id": str(session_id)},
    )
    return IssuedSession(
        session_id=session_id,
        family_id=verified.family_id,
        token=token,
        absolute_expires_at=verified.absolute_expires_at,
    )


async def revoke_session(
    session: AsyncSession, *, session_id: UUID, reason: str, now: datetime | None = None
) -> bool:
    """End ONE session. Returns whether this call was the one that ended it.

    Idempotent by CAS rather than by re-writing: a second sign-out must not overwrite the
    reason recorded by the first, because "signed_out" replacing "reuse_detected" would
    erase the only trace of a leak.
    """
    at = now or datetime.now(UTC)
    result = await session.execute(
        text(
            "UPDATE auth_sessions SET revoked_at = :now, revoked_reason = :reason, "
            "updated_at = :now WHERE id = :id AND revoked_at IS NULL"
        ),
        {"now": at, "reason": reason, "id": session_id},
    )
    return rowcount_of(result) == 1


async def revoke_family(
    session: AsyncSession, *, family_id: UUID, reason: str, now: datetime | None = None
) -> int:
    """End every session in one rotation family. Returns how many this call ended.

    Reached from the reuse detector and from a "sign out this device" action. Superseded
    rows are revoked too: a leaked token whose row is already superseded must not stay
    presentable as evidence-free.
    """
    at = now or datetime.now(UTC)
    result = await session.execute(
        text(
            "UPDATE auth_sessions SET revoked_at = :now, revoked_reason = :reason, "
            "updated_at = :now WHERE family_id = :fam AND revoked_at IS NULL"
        ),
        {"now": at, "reason": reason, "fam": family_id},
    )
    return rowcount_of(result)


async def revoke_subject_sessions(
    session: AsyncSession,
    *,
    realm: str,
    subject_id: UUID,
    reason: str = "subject_revoked",
    now: datetime | None = None,
) -> int:
    """Sign one person out everywhere, in one realm. Returns how many sessions ended.

    This is the function every privilege change owes a call to — password change,
    deactivation, role removal — and ASVS 5.0 V7 is explicit that entitlement changes must
    not leave live sessions behind. Scoped to ONE realm because the realms are separate
    systems: revoking an operator's console sessions has nothing to say about the client
    account they may also hold.
    """
    _refuse_unknown_realm(realm)
    at = now or datetime.now(UTC)
    result = await session.execute(
        text(
            "UPDATE auth_sessions SET revoked_at = :now, revoked_reason = :reason, "
            "updated_at = :now WHERE realm = :realm AND subject_id = :sub "
            "AND revoked_at IS NULL"
        ),
        {"now": at, "reason": reason, "realm": realm, "sub": subject_id},
    )
    count = rowcount_of(result)
    log.info(
        "auth_sessions_revoked",
        extra={"realm": realm, "subject_id": str(subject_id), "revoked": count},
    )
    return count


__all__ = [
    "IDLE_WRITE_FLOOR",
    "REALM_TIMEOUTS",
    "REFUSALS",
    "TOKEN_ENTROPY_BYTES",
    "IssuedSession",
    "RealmTimeouts",
    "SessionOutcome",
    "VerifiedSession",
    "issue_session",
    "new_token",
    "revoke_family",
    "revoke_session",
    "revoke_subject_sessions",
    "rotate_session",
    "token_fingerprint",
    "verify_session",
]
