"""Alembic environment. Sync psycopg driver (migrations don't need async).

DATABASE_URL comes from the process env or .env (same value the app uses). RLS
policies live IN migrations (hard rule 8) — autogenerate can never produce them,
which is exactly why every autogenerated diff is hand-reviewed (DEV-SETUP §5).
"""

import os
from pathlib import Path

from alembic import context
from apps.api.db.registry import Base
from apps.api.db.session import (
    MIGRATION_LOCK_TIMEOUT_MS,
    MIGRATION_STATEMENT_TIMEOUT_MS,
    migration_connect_args,
)
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

config = context.config
target_metadata = Base.metadata


def _database_url() -> str:
    # Migrations run as the OWNER role (DDL, roles, policies); the app's DATABASE_URL is
    # the unprivileged `calevate_app` role (NOSUPERUSER NOBYPASSRLS) and must not be used
    # here.
    #
    # THERE IS NO FALLBACK TO `DATABASE_URL`, and there used to be. The comment above has
    # always said migrations must never run as the app role, while the code immediately
    # below offered exactly that when the variable was absent — so a deploy that forgot
    # `ALEMBIC_DATABASE_URL` did not get "it is not set", it got a migration running as a
    # role that cannot create a policy, and a permission error naming whichever statement
    # happened to need the privilege first. A silently wrong role is worse than a refusal
    # on the one path whose whole job is to install the RLS that hard rule 1 rests on.
    url = os.environ.get("ALEMBIC_DATABASE_URL")
    if not url:
        raise RuntimeError(
            "ALEMBIC_DATABASE_URL is not set. Migrations run as the OWNER role; the app's "
            "DATABASE_URL is the unprivileged calevate_app role and will fail partway "
            "through, having already applied some DDL. Copy .env.example to .env."
        )
    # Alembic runs sync; the app may use an async driver suffix later.
    return url.replace("+asyncpg", "+psycopg")


def run_migrations_offline() -> None:
    # Offline mode EMITS SQL for a human to run, so there is no connection to hang a
    # connect-time option on and the two `SET`s go into the script instead — first, so
    # every statement after them is covered. Session-scoped rather than `SET LOCAL`: the
    # emitted file is one psql session under the single `BEGIN` this branch produces, and
    # a `SET LOCAL` would expire at the first `COMMIT` while the DDL kept coming.
    #
    # ⚠ A FULL `alembic upgrade head --sql` DOES NOT COMPLETE IN THIS REPO, and that is
    # older than these two lines: `versions/f4a1d0b6e29c_two_notices_two_toggles.py`
    # queries the database inside `upgrade()`, which offline mode has no connection for,
    # so the render dies there (reproduced 8 Sep 2026). The header this function emits is
    # therefore verified — `tests/statement_timeout_test.py` asserts it against a real
    # render — while everything past that revision is unreachable offline until that
    # migration stops reading.
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.execute(f"SET lock_timeout = {MIGRATION_LOCK_TIMEOUT_MS}")
        context.execute(f"SET statement_timeout = {MIGRATION_STATEMENT_TIMEOUT_MS}")
        context.run_migrations()


def run_migrations_online() -> None:
    # **BOTH TIMEOUTS, AT CONNECT, BECAUSE A MIGRATION IS HOW THIS SITE GOES DOWN.**
    #
    # `ALTER TABLE` takes ACCESS EXCLUSIVE, which conflicts with every other table lock.
    # With `lock_timeout` unset it waits FOREVER behind any open read — and the damage
    # does not start when it acquires the lock, it starts when it queues for it: every
    # query that arrives afterwards queues behind the waiting DDL, so the table is down
    # for as long as the read it is stuck behind runs. That is the outage hard rule 8's
    # "a migration in the same release as every new tenant table" makes a live path.
    # `MIGRATION_LOCK_TIMEOUT_MS` turns it into a failed deploy, which is recoverable by
    # re-running the deploy; the outage is not recoverable by anything.
    #
    # `statement_timeout` is the other half and is not redundant: `lock_timeout` bounds
    # only the WAIT, so a DDL that acquires its lock and then rewrites a large table
    # holds ACCESS EXCLUSIVE for the whole rewrite with nothing to stop it.
    #
    # Both are read from `apps.api.db.session` — see there for the numbers and why they
    # are those numbers, and for why a connect-time libpq option rather than two `SET`
    # statements (a `SET` is transactional, and `transaction_per_migration` below means a
    # rolled-back revision would take the GUCs with it).
    engine = create_engine(_database_url(), connect_args=migration_connect_args())
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            # ONE TRANSACTION PER REVISION, and this line is what makes three other
            # documents true rather than aspirational (P5.3).
            #
            # Alembic's default is False, and under PostgreSQL's transactional DDL that
            # means `context.begin_transaction()` below opens ONE transaction spanning the
            # whole `upgrade head` run. So a failure at revision 40 discarded the 39 that
            # had already succeeded — while `docs/DEPLOYMENT.md`, `scripts/vps-deploy.sh`
            # and `runbooks/deploy-failed.md` all told the operator, in the three places
            # they read at 3am, that "a failure leaves the database at the last revision
            # that fully applied".
            #
            # Worse, it was not even one clean transaction: 25 revisions use
            # `op.get_context().autocommit_block()`, 24 of them for `CREATE INDEX
            # CONCURRENTLY` (counted 8 Sep 2026; this said "three", which was true when it
            # was written and is not now), and each of those is an unconditional commit
            # point. Alembic's own docstring for
            # that method says so — "It is recommended that when an application includes
            # migrations with 'autocommit' blocks, that `transaction_per_migration` be
            # used." This repo has such blocks and did not use it, so a failed run could
            # leave an INVALID unique index on `credit_ledger` behind a commit boundary,
            # which is money (hard rule 7) and is exactly the "half-applied" state the
            # runbook promised could not exist.
            #
            # Chosen over editing the three documents to describe the worse property,
            # because the property they describe is the one hard rule 8 actually wants.
            transaction_per_migration=True,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
