"""Alembic environment. Sync psycopg driver (migrations don't need async).

DATABASE_URL comes from the process env or .env (same value the app uses). RLS
policies live IN migrations (hard rule 8) — autogenerate can never produce them,
which is exactly why every autogenerated diff is hand-reviewed (DEV-SETUP §5).
"""

import os
from pathlib import Path

from alembic import context
from apps.api.db.registry import Base
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv(Path(__file__).resolve().parent.parent / ".env")

config = context.config
target_metadata = Base.metadata


def _database_url() -> str:
    # Migrations run as the OWNER role (DDL, roles, policies); the app's DATABASE_URL is
    # the unprivileged `calevate_app` role (NOSUPERUSER NOBYPASSRLS) and must not be used
    # here.
    #
    # THERE IS NO FALLBACK TO `DATABASE_URL`, and there used to be. The comment above has
    # always said migrations must never run as the app role, while the code immediately
    # below offered exactly that when the variable was absent — so a deploy that forgot
    # `ALEMBIC_DATABASE_URL` did not get "it is not set", it got a migration running as a
    # role that cannot create a policy, and a permission error naming whichever statement
    # happened to need the privilege first. A silently wrong role is worse than a refusal
    # on the one path whose whole job is to install the RLS that hard rule 1 rests on.
    url = os.environ.get("ALEMBIC_DATABASE_URL")
    if not url:
        raise RuntimeError(
            "ALEMBIC_DATABASE_URL is not set. Migrations run as the OWNER role; the app's "
            "DATABASE_URL is the unprivileged calevate_app role and will fail partway "
            "through, having already applied some DDL. Copy .env.example to .env."
        )
    # Alembic runs sync; the app may use an async driver suffix later.
    return url.replace("+asyncpg", "+psycopg")


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_database_url())
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            # ONE TRANSACTION PER REVISION, and this line is what makes three other
            # documents true rather than aspirational (P5.3).
            #
            # Alembic's default is False, and under PostgreSQL's transactional DDL that
            # means `context.begin_transaction()` below opens ONE transaction spanning the
            # whole `upgrade head` run. So a failure at revision 40 discarded the 39 that
            # had already succeeded — while `docs/DEPLOYMENT.md`, `scripts/vps-deploy.sh`
            # and `runbooks/deploy-failed.md` all told the operator, in the three places
            # they read at 3am, that "a failure leaves the database at the last revision
            # that fully applied".
            #
            # Worse, it was not even one clean transaction: three revisions use
            # `op.get_context().autocommit_block()` for `CREATE INDEX CONCURRENTLY`, and
            # each of those is an unconditional commit point. Alembic's own docstring for
            # that method says so — "It is recommended that when an application includes
            # migrations with 'autocommit' blocks, that `transaction_per_migration` be
            # used." This repo has such blocks and did not use it, so a failed run could
            # leave an INVALID unique index on `credit_ledger` behind a commit boundary,
            # which is money (hard rule 7) and is exactly the "half-applied" state the
            # runbook promised could not exist.
            #
            # Chosen over editing the three documents to describe the worse property,
            # because the property they describe is the one hard rule 8 actually wants.
            transaction_per_migration=True,
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
